#!/bin/bash
# Guards deepar_flutter_plus's registration out of Simulator builds.
#
# WHY: DeepAR.framework (deepar_flutter_plus's vendored AR engine) ships a
# device-only Mach-O — confirmed via `lipo -info`, arm64/iphoneos slice
# only, no iphonesimulator slice at all (this is a vendor limitation, AR
# SDKs commonly skip simulator support since there's no real camera/motion
# sensors there). GeneratedPluginRegistrant.m unconditionally imports and
# registers deepar_flutter_plus regardless of platform, so linking Runner
# for the Simulator always fails with "Undefined symbol: _OBJC_CLASS_$_DeepAR"
# (and often a cascading "_OBJC_CLASS_$_CameraController" alongside it, from
# the same failed link step) — see the reaction-camera work's own
# investigation for how this was root-caused.
#
# GeneratedPluginRegistrant.m is regenerated by Flutter tooling on every
# `flutter pub get`/build (far more often than `pod install` reruns), so a
# one-time hand-edit gets silently wiped and this failure would resurface
# with no clue why. This script re-applies the guard on every single Xcode
# build via a Run Script build phase (see setup_simulator_patch.rb, which
# installs that phase once) — idempotent, safe to run every build.

set -euo pipefail

REGISTRANT="${SRCROOT}/Runner/GeneratedPluginRegistrant.m"

if [ ! -f "$REGISTRANT" ]; then
  echo "warning: GeneratedPluginRegistrant.m not found at $REGISTRANT — skipping DeepAR simulator guard"
  exit 0
fi

# Already guarded (either a fresh regeneration this patch hasn't touched
# yet, or a previous run of this same script) — check for our marker
# specifically, not just "#if" generally, so this is safe to re-run.
if grep -q "DEEPAR_SIMULATOR_GUARD" "$REGISTRANT"; then
  exit 0
fi

# Wraps the #import/#if __has_include block AND the @import + register
# call in a !TARGET_OS_SIMULATOR guard. Uses a Python inline script (not
# sed -i with multiline patterns, which is unreliable across BSD/GNU sed)
# for a precise, readable transform.
python3 - "$REGISTRANT" <<'PYEOF'
import re, sys

path = sys.argv[1]
with open(path) as f:
    src = f.read()

# The generated block looks like:
#   #if __has_include(<deepar_flutter_plus/DeepArPlugin.h>)
#   #import <deepar_flutter_plus/DeepArPlugin.h>
#   #endif
# ...
#   @import deepar_flutter_plus;
# ...
#   [DeepArPlugin registerWithRegistrar:...];
#
# Guard each DeepAR-referencing line individually with
# !TARGET_OS_SIMULATOR rather than trying to bracket the whole file, so
# this survives reordering of the generated plugin list across Flutter
# versions.
lines = src.split('\n')
out = []
guard_active = False
for line in lines:
    if 'deepar' in line.lower() or 'DeepAr' in line or 'DeepAR' in line:
        if not guard_active:
            out.append('#if !TARGET_OS_SIMULATOR  // DEEPAR_SIMULATOR_GUARD: device-only SDK, see patch_registrant_for_simulator.sh')
            guard_active = True
        out.append(line)
    else:
        if guard_active:
            out.append('#endif  // DEEPAR_SIMULATOR_GUARD')
            guard_active = False
        out.append(line)
if guard_active:
    out.append('#endif  // DEEPAR_SIMULATOR_GUARD')

with open(path, 'w') as f:
    f.write('\n'.join(out))

print(f"Patched {path}: guarded DeepAR registration out of Simulator builds")
PYEOF

# Second, separate problem from the one above: the "[CP] Embed Pods
# Frameworks" build phase (LAST phase, runs after this one — timing is
# fine) has its own Pods-Runner-frameworks-{Debug,Profile,Release}-
# input-files.xcfilelist, regenerated fresh (WITH DeepAR/deepar_flutter_plus
# listed) by `pod install` before every build, same as
# GeneratedPluginRegistrant.m above. Unlike that file, this can't be fixed
# with a preprocessor guard (#if isn't a thing in a plain file list) or
# from inside the Podfile's post_install (tried — CocoaPods' own
# "Integrate client project" step regenerates these files AFTER
# post_install runs, silently undoing any edit made there). So: strip the
# two DeepAR lines here, as a build-phase step, but ONLY when actually
# building for Simulator — $PLATFORM_NAME is available in any Xcode Run
# Script phase and reflects the SDK actually being built right now, so
# device builds are untouched (those frameworks legitimately exist and
# need to stay embedded there).
if [[ "${PLATFORM_NAME:-}" == *simulator* ]]; then
  for f in "${SRCROOT}/Pods/Target Support Files/Pods-Runner/Pods-Runner-frameworks-"*-input-files.xcfilelist; do
    if [ -f "$f" ]; then
      grep -v -E "DeepAR\.framework|deepar_flutter_plus\.framework" "$f" > "${f}.tmp" && mv "${f}.tmp" "$f"
    fi
  done
fi
