// ---------------------------------------------------------------------------
// Face mask filter — preset registry.
//
// REMOVAL: this whole feature lives under lib/features/face_filter/ plus a
// handful of clearly-marked `// FACE MASK FILTER:` lines in
// composer_screen.dart (see that file's _captureSingleShot, _CaptureCard,
// and the two CameraController(...) call sites). To remove entirely:
//   1. Delete this directory (lib/features/face_filter/).
//   2. Remove the `// FACE MASK FILTER:` lines from composer_screen.dart.
//   3. `flutter pub remove google_mlkit_face_detection`.
//   4. Remove the `assets/masks/` entry from pubspec.yaml and delete the
//      folder.
// ---------------------------------------------------------------------------

/// Only preset in use today — the monochrome web-pattern concealment mask:
/// charcoal hood, radial web, wide angular lenses.
///
/// Generated by tools/generate_web_mask.py rather than shipped as sourced
/// art. Two reasons: the lens centres end up at coordinates we choose, so
/// [kFaceMaskPresetCAnchor] is exact by construction; and it keeps the
/// asset original work in the web-mask visual language rather than a copy
/// of a licensed character costume, which is a real listing risk on the
/// Play Store.
const kFaceMaskPresetC = 'assets/masks/preset_c.png';

/// Where the EYES are inside the mask artwork, as fractions of the image.
///
/// EXACT, not measured: the artwork is generated by
/// tools/generate_web_mask.py, which places the lens centres and then
/// prints these three numbers. Re-run it after any change to the mask and
/// paste the values it reports.
///
/// This is what lets the mask be placed by its EYES rather than by its
/// bounding box. Before this the painter dropped the image's own centre
/// (0.5, 0.5) onto the detected eye midpoint and sized it off a fudge
/// factor, so the lenses never lined up with the wearer's eyes — the mask
/// sat low and small on the face.
class FaceMaskAnchor {
  const FaceMaskAnchor({
    required this.eyeSpanRatio,
    required this.eyeMidX,
    required this.eyeMidY,
  });

  /// Distance between the artwork's own eyes, as a fraction of image width.
  /// Draw width = detected eye distance / this, which is what makes the
  /// artwork's eyes land exactly on the real ones at any face size.
  final double eyeSpanRatio;

  /// The artwork's eye midpoint, as fractions of image width/height. The
  /// painter puts THIS point on the detected eye midpoint.
  final double eyeMidX;
  final double eyeMidY;
}

/// Preset C's anchor, as reported by tools/generate_web_mask.py.
const kFaceMaskPresetCAnchor = FaceMaskAnchor(
  eyeSpanRatio: 0.2930,
  eyeMidX: 0.5000,
  eyeMidY: 0.4375,
);

/// The anchor for a given preset path, or null for "no mask".
FaceMaskAnchor? anchorForPreset(String? path) =>
    path == kFaceMaskPresetC ? kFaceMaskPresetCAnchor : null;

/// Ordered list the composer's filter-switch button cycles through. `null`
/// means "no mask". Adding a future preset is exactly one line here — no
/// other file needs to change.
const kFaceMaskPresets = <String?>[null, kFaceMaskPresetC];
