WITH src(parent, slot, kind, txt) AS (VALUES
 ('A bruise with a story.',1,'photo','Show me where you got it'),
 ('A bruise with a story.',2,'text','Did it actually stop you from playing?'),
 ('A bruise with a story.',3,'photo','Show me the bruise up close'),
 ('A bruise with a story.',4,'text','How long till it heals?'),
 ('A bruise with a story.',5,'photo','Show me an older scar you still have'),
 ('A bruise with a story.',6,'text','Be honest — whose fault was it?'),

 ('Show the teammate you''d pass to every time. Face or not.',1,'photo','Show me where they usually stand'),
 ('Show the teammate you''d pass to every time. Face or not.',2,'text','Do they know you''d pick them first?'),
 ('Show the teammate you''d pass to every time. Face or not.',3,'photo','Show me their hands or their shoes'),
 ('Show the teammate you''d pass to every time. Face or not.',4,'text','How long have you played together?'),
 ('Show the teammate you''d pass to every time. Face or not.',5,'photo','Show me who''d pass to you'),
 ('Show the teammate you''d pass to every time. Face or not.',6,'text','Be honest — have they ever let you down?'),

 ('Show your grip — bat, racquet, ball, whatever.',1,'photo','Show me the rest of the equipment'),
 ('Show your grip — bat, racquet, ball, whatever.',2,'text','Did anyone teach you that grip?'),
 ('Show your grip — bat, racquet, ball, whatever.',3,'photo','Show me your hands on it, close up'),
 ('Show your grip — bat, racquet, ball, whatever.',4,'text','How long have you held it that way?'),
 ('Show your grip — bat, racquet, ball, whatever.',5,'photo','Show me someone else''s grip on the same thing'),
 ('Show your grip — bat, racquet, ball, whatever.',6,'text','Be honest — is your grip actually correct?'),

 ('The ground/court, empty or full, right now.',1,'photo','Show me who else is on it'),
 ('The ground/court, empty or full, right now.',2,'text','Empty or full — which do you prefer?'),
 ('The ground/court, empty or full, right now.',3,'photo','Show me the exact spot you stand'),
 ('The ground/court, empty or full, right now.',4,'text','How long have you played on this one?'),
 ('The ground/court, empty or full, right now.',5,'photo','Show me a different ground you''ve played on'),
 ('The ground/court, empty or full, right now.',6,'text','Be honest — is this ground actually good?'),

 ('The scoreboard from today.',1,'photo','Show me who''s watching it'),
 ('The scoreboard from today.',2,'text','Did your side win?'),
 ('The scoreboard from today.',3,'photo','Show me the number that matters most'),
 ('The scoreboard from today.',4,'text','How did the score get that bad or good?'),
 ('The scoreboard from today.',5,'photo','Show me the scoreboard from your worst game'),
 ('The scoreboard from today.',6,'text','Be honest — does the score even reflect the game?'),

 ('Your kit bag, unfiltered.',1,'photo','Show me what''s spilling out of it'),
 ('Your kit bag, unfiltered.',2,'text','What''s the one thing you never forget to pack?'),
 ('Your kit bag, unfiltered.',3,'photo','Show me the dirtiest thing inside'),
 ('Your kit bag, unfiltered.',4,'text','How long have you had this bag?'),
 ('Your kit bag, unfiltered.',5,'photo','Show me someone else''s kit bag for comparison'),
 ('Your kit bag, unfiltered.',6,'text','Be honest — is anything in there expired?'),

 ('Your shoes after today.',1,'photo','Show me where they''ve been'),
 ('Your shoes after today.',2,'text','Are they done for, honestly?'),
 ('Your shoes after today.',3,'photo','Show me the soles up close'),
 ('Your shoes after today.',4,'text','How many games have they survived?'),
 ('Your shoes after today.',5,'photo','Show me your first-ever pair for this sport'),
 ('Your shoes after today.',6,'text','Be honest — do they still smell fine?'),

 ('Your warm-up spot.',1,'photo','Show me what''s around it'),
 ('Your warm-up spot.',2,'text','Do you always warm up in the same place?'),
 ('Your warm-up spot.',3,'photo','Show me the ground from your warm-up spot'),
 ('Your warm-up spot.',4,'text','How long is your warm-up, honestly?'),
 ('Your warm-up spot.',5,'photo','Show me someone else warming up nearby'),
 ('Your warm-up spot.',6,'text','Be honest — do you ever skip it?'),

 ('SHOW YOUR FAVIOURITE SPORT AS SUCH',1,'photo','Show me where you play it most'),
 ('SHOW YOUR FAVIOURITE SPORT AS SUCH',2,'text','When did you start playing it?'),
 ('SHOW YOUR FAVIOURITE SPORT AS SUCH',3,'photo','Show me your gear for it'),
 ('SHOW YOUR FAVIOURITE SPORT AS SUCH',4,'text','Who got you into it?'),
 ('SHOW YOUR FAVIOURITE SPORT AS SUCH',5,'photo','Show me a sport you''d never play'),
 ('SHOW YOUR FAVIOURITE SPORT AS SUCH',6,'text','Be honest — are you actually good at it?'),

 ('Show the weight you''re on today. Not the max, today''s.',1,'photo','Show me the rest of the rack'),
 ('Show the weight you''re on today. Not the max, today''s.',2,'text','Is today lighter than usual?'),
 ('Show the weight you''re on today. Not the max, today''s.',3,'photo','Show me the plates up close'),
 ('Show the weight you''re on today. Not the max, today''s.',4,'text','How long to get to this weight?'),
 ('Show the weight you''re on today. Not the max, today''s.',5,'photo','Show me your max, whenever that was'),
 ('Show the weight you''re on today. Not the max, today''s.',6,'text','Be honest — could you go heavier today?'),

 ('Show your gym at its most crowded hour.',1,'photo','Show me the queue for your machine'),
 ('Show your gym at its most crowded hour.',2,'text','What time do you actually prefer?'),
 ('Show your gym at its most crowded hour.',3,'photo','Show me the corner nobody fights for'),
 ('Show your gym at its most crowded hour.',4,'text','How long have you trained at this hour?'),
 ('Show your gym at its most crowded hour.',5,'photo','Show me the gym empty, if you''ve seen it'),
 ('Show your gym at its most crowded hour.',6,'text','Be honest — do you avoid eye contact here?'),

 ('Something you can do now that you couldn''t in June.',1,'photo','Show me you doing it right now'),
 ('Something you can do now that you couldn''t in June.',2,'text','What changed to make it possible?'),
 ('Something you can do now that you couldn''t in June.',3,'photo','Show me where you first tried it'),
 ('Something you can do now that you couldn''t in June.',4,'text','How long did it take?'),
 ('Something you can do now that you couldn''t in June.',5,'photo','Show me something you still can''t do'),
 ('Something you can do now that you couldn''t in June.',6,'text','Be honest — did you think it''d take longer?'),

 ('The machine you avoid.',1,'photo','Show me it, empty or not'),
 ('The machine you avoid.',2,'text','What happened with it?'),
 ('The machine you avoid.',3,'photo','Show me the machine you actually love'),
 ('The machine you avoid.',4,'text','How long have you been avoiding it?'),
 ('The machine you avoid.',5,'photo','Show me someone using it right now'),
 ('The machine you avoid.',6,'text','Be honest — are you scared of it?'),

 ('The shoes you lift in.',1,'photo','Show me the soles'),
 ('The shoes you lift in.',2,'text','How long have they lasted?'),
 ('The shoes you lift in.',3,'photo','Show me the laces up close'),
 ('The shoes you lift in.',4,'text','Why these and not running shoes?'),
 ('The shoes you lift in.',5,'photo','Show me your other gym shoes'),
 ('The shoes you lift in.',6,'text','Be honest — do they still fit right?'),

 ('Your 6am alarm screenshot.',1,'photo','Show me your face right after it went off'),
 ('Your 6am alarm screenshot.',2,'text','Did you actually get up first try?'),
 ('Your 6am alarm screenshot.',3,'photo','Show me the snooze count'),
 ('Your 6am alarm screenshot.',4,'text','How many times has it failed this week?'),
 ('Your 6am alarm screenshot.',5,'photo','Show me your alarm from a day you skipped'),
 ('Your 6am alarm screenshot.',6,'text','Be honest — is 6am even necessary?'),

 ('Your post-workout meal.',1,'photo','Show me the kitchen or mess it came from'),
 ('Your post-workout meal.',2,'text','Is this actually enough protein?'),
 ('Your post-workout meal.',3,'photo','Show me it half-eaten'),
 ('Your post-workout meal.',4,'text','How long after training do you eat?'),
 ('Your post-workout meal.',5,'photo','Show me your pre-workout meal too'),
 ('Your post-workout meal.',6,'text','Be honest — did you earn this meal today?'),

 ('Your water bottle situation.',1,'photo','Show me how full it actually is'),
 ('Your water bottle situation.',2,'text','How many times do you refill it a day?'),
 ('Your water bottle situation.',3,'photo','Show me the scratches or stickers on it'),
 ('Your water bottle situation.',4,'text','How old is this bottle?'),
 ('Your water bottle situation.',5,'photo','Show me someone else''s bottle nearby'),
 ('Your water bottle situation.',6,'text','Be honest — when did you last wash it?'),

 ('A part you replaced yourself.',1,'photo','Show me the tool you used'),
 ('A part you replaced yourself.',2,'text','Did you look up how first?'),
 ('A part you replaced yourself.',3,'photo','Show me the old part you took off'),
 ('A part you replaced yourself.',4,'text','How long did it take you?'),
 ('A part you replaced yourself.',5,'photo','Show me a part you''re scared to touch'),
 ('A part you replaced yourself.',6,'text','Be honest — did you get it right first try?'),

 ('Engine bay / chain / whatever you''re most proud of.',1,'photo','Show me the rest of the machine around it'),
 ('Engine bay / chain / whatever you''re most proud of.',2,'text','How long did it take to get it this clean?'),
 ('Engine bay / chain / whatever you''re most proud of.',3,'photo','Show me it up close, no filter'),
 ('Engine bay / chain / whatever you''re most proud of.',4,'text','Who taught you to maintain it?'),
 ('Engine bay / chain / whatever you''re most proud of.',5,'photo','Show me the part you''re least proud of'),
 ('Engine bay / chain / whatever you''re most proud of.',6,'text','Be honest — did you do this yourself?'),

 ('Show something you fixed with the wrong tool.',1,'photo','Show me the actual tool you used'),
 ('Show something you fixed with the wrong tool.',2,'text','Did it actually hold?'),
 ('Show something you fixed with the wrong tool.',3,'photo','Show me the fix up close'),
 ('Show something you fixed with the wrong tool.',4,'text','Why didn''t you have the right one?'),
 ('Show something you fixed with the wrong tool.',5,'photo','Show me the right tool, if you own it now'),
 ('Show something you fixed with the wrong tool.',6,'text','Be honest — would you do it that way again?'),

 ('Show your odometer.',1,'photo','Show me the road you''re on right now'),
 ('Show your odometer.',2,'text','How many of those km were today?'),
 ('Show your odometer.',3,'photo','Show me the odometer up close'),
 ('Show your odometer.',4,'text','How long have you owned it?'),
 ('Show your odometer.',5,'photo','Show me someone else''s odometer for comparison'),
 ('Show your odometer.',6,'text','Be honest — is that number higher than you thought?'),

 ('The best road you''ve found near Bengaluru.',1,'photo','Show me the turn onto it'),
 ('The best road you''ve found near Bengaluru.',2,'text','Who told you about it?'),
 ('The best road you''ve found near Bengaluru.',3,'photo','Show me the road surface up close'),
 ('The best road you''ve found near Bengaluru.',4,'text','How far is it from campus?'),
 ('The best road you''ve found near Bengaluru.',5,'photo','Show me the worst road you''ve ridden'),
 ('The best road you''ve found near Bengaluru.',6,'text','Be honest — are you gatekeeping this one?'),

 ('The dirtiest part of it.',1,'photo','Show me the cleanest part for contrast'),
 ('The dirtiest part of it.',2,'text','When did you last actually clean it?'),
 ('The dirtiest part of it.',3,'photo','Show me the dirt up close'),
 ('The dirtiest part of it.',4,'text','How did it get this bad?'),
 ('The dirtiest part of it.',5,'photo','Show me someone else''s, cleaner or worse'),
 ('The dirtiest part of it.',6,'text','Be honest — are you going to clean it today?'),

 ('Your helmet, wherever it''s sitting.',1,'photo','Show me the room around it'),
 ('Your helmet, wherever it''s sitting.',2,'text','How old is it?'),
 ('Your helmet, wherever it''s sitting.',3,'photo','Show me the visor up close'),
 ('Your helmet, wherever it''s sitting.',4,'text','Has it ever actually saved you?'),
 ('Your helmet, wherever it''s sitting.',5,'photo','Show me someone else''s helmet nearby'),
 ('Your helmet, wherever it''s sitting.',6,'text','Be honest — do you always wear it?'),

 ('Your machine. Any angle, right now.',1,'photo','Show me it from the angle you never post'),
 ('Your machine. Any angle, right now.',2,'text','How long have you had it?'),
 ('Your machine. Any angle, right now.',3,'photo','Show me the odometer or the tank'),
 ('Your machine. Any angle, right now.',4,'text','What made you pick this one?'),
 ('Your machine. Any angle, right now.',5,'photo','Show me the machine you actually want next'),
 ('Your machine. Any angle, right now.',6,'text','Be honest — does it have a name?'),

 ('Show the corner of campus you rehearse in.',1,'photo','Show me who else is rehearsing there'),
 ('Show the corner of campus you rehearse in.',2,'text','Why that corner and not a studio?'),
 ('Show the corner of campus you rehearse in.',3,'photo','Show me the floor up close'),
 ('Show the corner of campus you rehearse in.',4,'text','How long have you used this spot?'),
 ('Show the corner of campus you rehearse in.',5,'photo','Show me a corner you''d rather have'),
 ('Show the corner of campus you rehearse in.',6,'text','Be honest — do people stop and stare?'),

 ('Show your shoes mid-practice.',1,'photo','Show me the floor they''re standing on'),
 ('Show your shoes mid-practice.',2,'text','How long have these lasted you?'),
 ('Show your shoes mid-practice.',3,'photo','Show me the wear on the soles'),
 ('Show your shoes mid-practice.',4,'text','When did you last replace a pair?'),
 ('Show your shoes mid-practice.',5,'photo','Show me a dancer''s shoes next to yours'),
 ('Show your shoes mid-practice.',6,'text','Be honest — do your feet actually hurt right now?'),

 ('Something that hurt after a session.',1,'photo','Show me where it hurts'),
 ('Something that hurt after a session.',2,'text','Did you stretch enough today?'),
 ('Something that hurt after a session.',3,'photo','Show me it up close'),
 ('Something that hurt after a session.',4,'text','How many days has it hurt?'),
 ('Something that hurt after a session.',5,'photo','Show me something that used to hurt but doesn''t anymore'),
 ('Something that hurt after a session.',6,'text','Be honest — are you dancing through it anyway?'),

 ('The mirror you practice in front of.',1,'photo','Show me what''s reflected behind you'),
 ('The mirror you practice in front of.',2,'text','Do you like watching yourself, honestly?'),
 ('The mirror you practice in front of.',3,'photo','Show me a mark or crack on the mirror'),
 ('The mirror you practice in front of.',4,'text','How long have you used this mirror?'),
 ('The mirror you practice in front of.',5,'photo','Show me yourself in a different mirror'),
 ('The mirror you practice in front of.',6,'text','Be honest — do you avoid certain angles?'),

 ('The move you''ve been failing at — one frozen frame.',1,'photo','Show me where you keep failing it'),
 ('The move you''ve been failing at — one frozen frame.',2,'text','How many times have you tried today?'),
 ('The move you''ve been failing at — one frozen frame.',3,'photo','Show me your feet mid-attempt'),
 ('The move you''ve been failing at — one frozen frame.',4,'text','Who''s shown you how to fix it?'),
 ('The move you''ve been failing at — one frozen frame.',5,'photo','Show me a move you''ve actually nailed'),
 ('The move you''ve been failing at — one frozen frame.',6,'text','Be honest — is it the move or is it you?'),

 ('Your costume from the last performance.',1,'photo','Show me where it''s hanging now'),
 ('Your costume from the last performance.',2,'text','Did it fit right on the day?'),
 ('Your costume from the last performance.',3,'photo','Show me the detail you loved most'),
 ('Your costume from the last performance.',4,'text','Who made or picked it?'),
 ('Your costume from the last performance.',5,'photo','Show me the costume you wish you''d worn instead'),
 ('Your costume from the last performance.',6,'text','Be honest — would you wear it again?'),

 ('Your playlist for practice.',1,'photo','Show me your headphones or speaker'),
 ('Your playlist for practice.',2,'text','What''s the one song that''s always on it?'),
 ('Your playlist for practice.',3,'photo','Show me the playlist screen itself'),
 ('Your playlist for practice.',4,'text','How long has this playlist existed?'),
 ('Your playlist for practice.',5,'photo','Show me someone else''s practice playlist'),
 ('Your playlist for practice.',6,'text','Be honest — do you skip the same song every time?'),

 ('Your practice space, empty.',1,'photo','Show me it full, from another day'),
 ('Your practice space, empty.',2,'text','What time is it emptiest?'),
 ('Your practice space, empty.',3,'photo','Show me the floor marks or scuffs'),
 ('Your practice space, empty.',4,'text','How long have you practiced here?'),
 ('Your practice space, empty.',5,'photo','Show me a space you''d rather practice in'),
 ('Your practice space, empty.',6,'text','Be honest — does it feel different when it''s empty?')
)
INSERT INTO public.ping_prompts (prompt_text, daily_prompt_id, pool, prompt_kind, active, created_at)
SELECT s.txt, dp.id, 'linked', s.kind, true, now() + (s.slot * interval '1 millisecond')
FROM src s
JOIN public.daily_prompts dp ON dp.prompt_text = s.parent AND dp.active
WHERE NOT EXISTS (
  SELECT 1 FROM public.ping_prompts pp
   WHERE pp.daily_prompt_id = dp.id AND pp.prompt_text = s.txt
);
