WITH src(parent, slot, kind, txt) AS (VALUES
 ('Confess the most harmless thing you got away with',1,'photo','Show me where it happened'),
 ('Confess the most harmless thing you got away with',2,'text','Did anyone ever find out?'),
 ('Confess the most harmless thing you got away with',3,'photo','Show me the evidence, if any survived'),
 ('Confess the most harmless thing you got away with',4,'text','How long ago was this?'),
 ('Confess the most harmless thing you got away with',5,'photo','Show me your "innocent" face'),
 ('Confess the most harmless thing you got away with',6,'text','Be honest — would you do it again?'),
 ('What''s a small thing nobody knows about you?',1,'photo','Show me something in your room that hints at it'),
 ('What''s a small thing nobody knows about you?',2,'text','Who would be most surprised?'),
 ('What''s a small thing nobody knows about you?',3,'photo','Show me the object most connected to it'),
 ('What''s a small thing nobody knows about you?',4,'text','How long have you kept it quiet?'),
 ('What''s a small thing nobody knows about you?',5,'photo','Show me your face reading this'),
 ('What''s a small thing nobody knows about you?',6,'text','What''s the second thing nobody knows?'),
 ('What''s something you wish people understood about you?',1,'photo','Show me where you are when you feel most misunderstood'),
 ('What''s something you wish people understood about you?',2,'text','Who do you most wish got it?'),
 ('What''s something you wish people understood about you?',3,'photo','Show me something that represents the real you'),
 ('What''s something you wish people understood about you?',4,'text','When did you stop trying to explain?'),
 ('What''s something you wish people understood about you?',5,'photo','Show me what you look like right now'),
 ('What''s something you wish people understood about you?',6,'text','What do people get right about you?'),
 ('What''s something you''ve never told anyone here?',1,'photo','Show me where you are right now'),
 ('What''s something you''ve never told anyone here?',2,'text','Why here, why now?'),
 ('What''s something you''ve never told anyone here?',3,'photo','Show me the thing closest to you'),
 ('What''s something you''ve never told anyone here?',4,'text','How long have you been carrying it?'),
 ('What''s something you''ve never told anyone here?',5,'photo','Show me your view'),
 ('What''s something you''ve never told anyone here?',6,'text','Does anyone at home know?'),
 ('Best hidden spot on campus, don''t gatekeep',1,'photo','Show me the path to get there'),
 ('Best hidden spot on campus, don''t gatekeep',2,'text','Who showed it to you?'),
 ('Best hidden spot on campus, don''t gatekeep',3,'photo','Show me the view from the spot'),
 ('Best hidden spot on campus, don''t gatekeep',4,'text','How often are you actually there?'),
 ('Best hidden spot on campus, don''t gatekeep',5,'photo','Show me where you''re sitting right now instead'),
 ('Best hidden spot on campus, don''t gatekeep',6,'text','Be honest — are you annoyed you shared it?'),
 ('Biggest lie you''ve told to skip a class?',1,'photo','Show me where you went instead'),
 ('Biggest lie you''ve told to skip a class?',2,'text','Did it work?'),
 ('Biggest lie you''ve told to skip a class?',3,'photo','Show me the class you skipped, if you''re near it'),
 ('Biggest lie you''ve told to skip a class?',4,'text','Have you reused it?'),
 ('Biggest lie you''ve told to skip a class?',5,'photo','Show me your attendance screen'),
 ('Biggest lie you''ve told to skip a class?',6,'text','What''s the lie you''d never dare use?'),
 ('Hottest take about the canteen food?',1,'photo','Show me what you''re eating right now'),
 ('Hottest take about the canteen food?',2,'text','What''s the one thing that''s actually good?'),
 ('Hottest take about the canteen food?',3,'photo','Show me the counter you avoid'),
 ('Hottest take about the canteen food?',4,'text','How many times a week do you eat there?'),
 ('Hottest take about the canteen food?',5,'photo','Show me your alternative'),
 ('Hottest take about the canteen food?',6,'text','Be honest — is it the food or the queue?'),
 ('Is the attendance policy actually fair? Go.',1,'photo','Show me your attendance percentage'),
 ('Is the attendance policy actually fair? Go.',2,'text','Have you ever been short?'),
 ('Is the attendance policy actually fair? Go.',3,'photo','Show me the class you''d never skip'),
 ('Is the attendance policy actually fair? Go.',4,'text','What would you change about it?'),
 ('Is the attendance policy actually fair? Go.',5,'photo','Show me where you are during the class you skip most'),
 ('Is the attendance policy actually fair? Go.',6,'text','Be honest — is 75% actually hard?'),
 ('Most overhyped fest event?',1,'photo','Show me a photo you have from it'),
 ('Most overhyped fest event?',2,'text','Did you still go?'),
 ('Most overhyped fest event?',3,'photo','Show me where you were standing'),
 ('Most overhyped fest event?',4,'text','What was actually good that day?'),
 ('Most overhyped fest event?',5,'photo','Show me what you''d rather have been doing'),
 ('Most overhyped fest event?',6,'text','Would you go again next year?'),
 ('Most overrated course in your branch?',1,'photo','Show me the textbook or slides'),
 ('Most overrated course in your branch?',2,'text','What''s it supposed to teach vs. what it does?'),
 ('Most overrated course in your branch?',3,'photo','Show me your notes from it'),
 ('Most overrated course in your branch?',4,'text','What''s your actual grade in it?'),
 ('Most overrated course in your branch?',5,'photo','Show me the course you''d defend instead'),
 ('Most overrated course in your branch?',6,'text','Be honest — is it the course or the prof?'),
 ('Most useless facility we''re paying for?',1,'photo','Show it to me, wherever it is'),
 ('Most useless facility we''re paying for?',2,'text','Have you ever actually used it?'),
 ('Most useless facility we''re paying for?',3,'photo','Show me what it looks like when nobody''s there'),
 ('Most useless facility we''re paying for?',4,'text','What should it be instead?'),
 ('Most useless facility we''re paying for?',5,'photo','Show me the facility you do use'),
 ('Most useless facility we''re paying for?',6,'text','Be honest — is anyone using it?'),
 ('Settle it: which branch has it hardest?',1,'photo','Show me your timetable'),
 ('Settle it: which branch has it hardest?',2,'text','What''s your honest weekly workload?'),
 ('Settle it: which branch has it hardest?',3,'photo','Show me your current assignment pile'),
 ('Settle it: which branch has it hardest?',4,'text','Which branch do you secretly respect?'),
 ('Settle it: which branch has it hardest?',5,'photo','Show me your desk at its worst this week'),
 ('Settle it: which branch has it hardest?',6,'text','Be honest — is yours actually the hardest?'),
 ('What campus rule does literally everyone break?',1,'photo','Show me where it gets broken most'),
 ('What campus rule does literally everyone break?',2,'text','Have you been caught?'),
 ('What campus rule does literally everyone break?',3,'photo','Show me the sign, if there is one'),
 ('What campus rule does literally everyone break?',4,'text','Does anyone enforce it?'),
 ('What campus rule does literally everyone break?',5,'photo','Show me you breaking it right now'),
 ('What campus rule does literally everyone break?',6,'text','What''s the one rule nobody breaks?'),
 ('What does everyone get wrong about your branch?',1,'photo','Show me what your branch actually looks like day to day'),
 ('What does everyone get wrong about your branch?',2,'text','What''s the assumption you hear most?'),
 ('What does everyone get wrong about your branch?',3,'photo','Show me your lab or workspace'),
 ('What does everyone get wrong about your branch?',4,'text','What made you pick it?'),
 ('What does everyone get wrong about your branch?',5,'photo','Show me your current screen or sheet'),
 ('What does everyone get wrong about your branch?',6,'text','Would you switch if you could?'),
 ('What''s a campus secret you''ll only say anonymously?',1,'photo','Show me where you are saying this from'),
 ('What''s a campus secret you''ll only say anonymously?',2,'text','How many people know?'),
 ('What''s a campus secret you''ll only say anonymously?',3,'photo','Show me anything connected to it'),
 ('What''s a campus secret you''ll only say anonymously?',4,'text','How long have you known?'),
 ('What''s a campus secret you''ll only say anonymously?',5,'photo','Show me your surroundings right now'),
 ('What''s a campus secret you''ll only say anonymously?',6,'text','Would you say it with your name on it?'),
 ('What''s a class everyone sleeps through?',1,'photo','Show me the room'),
 ('What''s a class everyone sleeps through?',2,'text','Have you slept through it?'),
 ('What''s a class everyone sleeps through?',3,'photo','Show me your notes from that class'),
 ('What''s a class everyone sleeps through?',4,'text','What time is it scheduled?'),
 ('What''s a class everyone sleeps through?',5,'photo','Show me what you do instead'),
 ('What''s a class everyone sleeps through?',6,'text','Be honest — is it the prof or the hour?'),
 ('What''s something our college pretends is great but isn''t?',1,'photo','Show me it'),
 ('What''s something our college pretends is great but isn''t?',2,'text','What''s the gap between claim and reality?'),
 ('What''s something our college pretends is great but isn''t?',3,'photo','Show me the brochure version vs. the real one'),
 ('What''s something our college pretends is great but isn''t?',4,'text','Who still believes it?'),
 ('What''s something our college pretends is great but isn''t?',5,'photo','Show me what actually is great here'),
 ('What''s something our college pretends is great but isn''t?',6,'text','Would you still recommend RVCE?'),
 ('What''s the most overrated thing about our college?',1,'photo','Show me the thing itself'),
 ('What''s the most overrated thing about our college?',2,'text','What do people expect vs. get?'),
 ('What''s the most overrated thing about our college?',3,'photo','Show me the most underrated thing instead'),
 ('What''s the most overrated thing about our college?',4,'text','Did it affect your choice to come here?'),
 ('What''s the most overrated thing about our college?',5,'photo','Show me where you are on campus right now'),
 ('What''s the most overrated thing about our college?',6,'text','Be honest — is it still worth it?'),
 ('Which branch thinks they''re superior but isn''t?',1,'photo','Show me your own branch''s reality'),
 ('Which branch thinks they''re superior but isn''t?',2,'text','What gives it away?'),
 ('Which branch thinks they''re superior but isn''t?',3,'photo','Show me your timetable for comparison'),
 ('Which branch thinks they''re superior but isn''t?',4,'text','Which branch is genuinely underrated?'),
 ('Which branch thinks they''re superior but isn''t?',5,'photo','Show me your workload right now'),
 ('Which branch thinks they''re superior but isn''t?',6,'text','Be honest — does your branch do it too?'),
 ('Which subject is a complete waste of time?',1,'photo','Show me the textbook'),
 ('Which subject is a complete waste of time?',2,'text','What would you replace it with?'),
 ('Which subject is a complete waste of time?',3,'photo','Show me your notes for it'),
 ('Which subject is a complete waste of time?',4,'text','How many hours a week does it take?'),
 ('Which subject is a complete waste of time?',5,'photo','Show me the subject you actually like'),
 ('Which subject is a complete waste of time?',6,'text','Be honest — will you remember any of it?'),
 ('Proof of what you were supposed to be doing right now.',1,'photo','Show me what you''re doing instead'),
 ('Proof of what you were supposed to be doing right now.',2,'text','How far behind are you?'),
 ('Proof of what you were supposed to be doing right now.',3,'photo','Show me the deadline'),
 ('Proof of what you were supposed to be doing right now.',4,'text','When did you last actually start it?'),
 ('Proof of what you were supposed to be doing right now.',5,'photo','Show me your desk right now'),
 ('Proof of what you were supposed to be doing right now.',6,'text','Be honest — will you finish it tonight?'),
 ('Show the exact spot you were sitting when you got your RVCE result.',1,'photo','Show me who was with you'),
 ('Show the exact spot you were sitting when you got your RVCE result.',2,'text','What was the first thing you said?'),
 ('Show the exact spot you were sitting when you got your RVCE result.',3,'photo','Show me the screen you read it on'),
 ('Show the exact spot you were sitting when you got your RVCE result.',4,'text','Was RVCE your first choice?'),
 ('Show the exact spot you were sitting when you got your RVCE result.',5,'photo','Show me where you''re sitting now'),
 ('Show the exact spot you were sitting when you got your RVCE result.',6,'text','Be honest — relief or disappointment?'),
 ('Something on this campus that shouldn''t still be there.',1,'photo','Show me it from another angle'),
 ('Something on this campus that shouldn''t still be there.',2,'text','How long has it been like that?'),
 ('Something on this campus that shouldn''t still be there.',3,'photo','Show me what''s around it'),
 ('Something on this campus that shouldn''t still be there.',4,'text','Has anyone ever complained?'),
 ('Something on this campus that shouldn''t still be there.',5,'photo','Show me something here that was fixed'),
 ('Something on this campus that shouldn''t still be there.',6,'text','What should be there instead?'),
 ('The most cursed thing in your bag.',1,'photo','Show me the rest of the bag'),
 ('The most cursed thing in your bag.',2,'text','How long has it been in there?'),
 ('The most cursed thing in your bag.',3,'photo','Show me it properly, close up'),
 ('The most cursed thing in your bag.',4,'text','Why haven''t you thrown it out?'),
 ('The most cursed thing in your bag.',5,'photo','Show me the cleanest thing in there'),
 ('The most cursed thing in your bag.',6,'text','Be honest — when did you last empty it?'),
 ('The view from exactly where you''re sitting.',1,'photo','Now turn around and show me behind you'),
 ('The view from exactly where you''re sitting.',2,'text','How long have you been there?'),
 ('The view from exactly where you''re sitting.',3,'photo','Show me what''s on the table or desk'),
 ('The view from exactly where you''re sitting.',4,'text','Is this your usual spot?'),
 ('The view from exactly where you''re sitting.',5,'photo','Show me your feet'),
 ('The view from exactly where you''re sitting.',6,'text','Be honest — should you be somewhere else?'),
 ('Whatever is closest to your left hand.',1,'photo','Now show me what''s closest to your right'),
 ('Whatever is closest to your left hand.',2,'text','Why is that the closest thing?'),
 ('Whatever is closest to your left hand.',3,'photo','Show me it properly'),
 ('Whatever is closest to your left hand.',4,'text','How often do you use it?'),
 ('Whatever is closest to your left hand.',5,'photo','Show me the whole surface it''s on'),
 ('Whatever is closest to your left hand.',6,'text','Be honest — is it yours?'),
 ('Your battery percentage + what you''re doing about it.',1,'photo','Show me your charger situation'),
 ('Your battery percentage + what you''re doing about it.',2,'text','How long till it dies?'),
 ('Your battery percentage + what you''re doing about it.',3,'photo','Show me your screen time'),
 ('Your battery percentage + what you''re doing about it.',4,'text','What drained it?'),
 ('Your battery percentage + what you''re doing about it.',5,'photo','Show me the nearest plug point'),
 ('Your battery percentage + what you''re doing about it.',6,'text','Be honest — do you carry a cable?'),
 ('Your screen right now. No cleanup.',1,'photo','Show me your tab count'),
 ('Your screen right now. No cleanup.',2,'text','What were you actually doing?'),
 ('Your screen right now. No cleanup.',3,'photo','Show me your notifications'),
 ('Your screen right now. No cleanup.',4,'text','How long has that tab been open?'),
 ('Your screen right now. No cleanup.',5,'photo','Show me your desktop wallpaper'),
 ('Your screen right now. No cleanup.',6,'text','Be honest — did you close anything first?')
),
target AS (
  SELECT DISTINCT ON (dp.prompt_text) dp.id, dp.prompt_text
    FROM public.daily_prompts dp
   WHERE dp.community_id IS NULL
   ORDER BY dp.prompt_text, dp.created_at
)
INSERT INTO public.ping_prompts (prompt_text, daily_prompt_id, pool, prompt_kind, active, created_at)
SELECT s.txt, t.id, 'linked', s.kind, true, now() + (s.slot * interval '1 millisecond')
FROM src s
JOIN target t ON t.prompt_text = s.parent
WHERE NOT EXISTS (
  SELECT 1 FROM public.ping_prompts pp
   WHERE pp.daily_prompt_id = t.id AND pp.prompt_text = s.txt
);
