-- Seed ping_sheet_prompts from the app's own hardcoded lists, so the
-- dashboard opens with the real content the app already ships rather than an
-- empty table. Idempotent: skipped entirely if the table already has rows,
-- so re-running never duplicates or clobbers dashboard edits.
insert into public.ping_sheet_prompts (scope, prompt_text, sort_order)
select v.scope, v.prompt_text, v.sort_order
from (values
  ('everyone', 'Hey, want to hang out? 👋', 0),
  ('everyone', 'Coffee sometime? ☕', 1),
  ('everyone', 'Let''s catch up soon!', 2),
  ('everyone', 'Miss you! Where you been?', 3),
  ('everyone', 'Long time no see!', 4),
  ('everyone', 'What are you up to?', 5),
  ('everyone', 'Study session? 📚', 6),
  ('everyone', 'Gym buddy? 💪', 7),
  ('everyone', 'Lunch today? 🍕', 8),
  ('everyone', 'Movie this weekend? 🎬', 9),
  ('everyone', 'We should hang!', 10),
  ('everyone', 'You free this weekend?', 11),
  ('everyone', 'That post was 🔥', 12),
  ('everyone', 'You''re hilarious 😂', 13),
  ('everyone', 'Love your vibe ✨', 14),
  ('everyone', 'Great photos! 📸', 15),
  ('everyone', 'Same vibes honestly 🙌', 16),
  ('everyone', 'Saw your post, let''s talk!', 17),
  ('everyone', 'Caught my eye 👀', 18),
  ('everyone', 'We should talk more 😊', 19),
  ('everyone', 'Collab on something? 🎯', 20),
  ('everyone', 'You good? Checking in 🤍', 21),
  ('everyone', 'Show me your view right now 🌅', 22),
  ('everyone', 'What''s on your desk? 🗂️', 23),
  ('everyone', 'Show me what you''re eating 🍜', 24),
  ('everyone', 'Outfit check 👟', 25),
  ('everyone', 'Where are you sitting right now? 📍', 26),
  ('everyone', 'Show me your screen 💻', 27),
  ('everyone', 'What''s the sky doing? ☁️', 28),
  ('everyone', 'Selfie, no filter, right now 📸', 29),
  ('everyone', 'Show me the last thing that made you laugh 😭', 30),
  ('everyone', 'Proof you''re actually studying 📖', 31),
  ('everyone', 'Rate my day out of 10 👀', 32),
  ('everyone', 'Guess where I am 🗺️', 33),
  ('everyone', 'Bet you can''t top this 😤', 34),
  ('everyone', 'Unhinged thought of the day?', 35),
  ('everyone', 'Drop your current song 🎧', 36),
  ('everyone', 'Most chaotic thing today?', 37),
  ('everyone', 'Say something in 3 words', 38),
  ('everyone', 'You made my week better 🤍', 39),
  ('everyone', 'Genuinely glad you exist', 40),
  ('everyone', 'You''re better at this than you think', 41),
  ('everyone', 'Thanks for showing up 🙏', 42),
  ('everyone', 'You''ve been carrying it lately 💪', 43),
  ('everyone', 'Proud of you, seriously', 44),
  ('anonymous', 'I relate to this so much', 0),
  ('anonymous', 'You''re not alone in feeling this', 1),
  ('anonymous', 'This needed to be said', 2),
  ('anonymous', 'Sending you good vibes 🌙', 3),
  ('anonymous', 'We should talk (anon)', 4),
  ('anonymous', 'Your words matter', 5),
  ('anonymous', 'Same here, honestly', 6),
  ('anonymous', 'Thank you for sharing this', 7),
  ('anonymous', 'I see you 👁️', 8),
  ('anonymous', 'This hit different', 9),
  ('anonymous', 'Felt this in my chest', 10),
  ('anonymous', 'You''re braver than you think', 11),
  ('anonymous', 'Me too, honestly', 12),
  ('anonymous', 'Hope you''re okay 🤍', 13),
  ('anonymous', 'This is real. I feel it too', 14),
  ('anonymous', 'Show me where you are right now 🌙', 15),
  ('anonymous', 'What does your night look like? ✨', 16),
  ('anonymous', 'Show me something small that helped today', 17),
  ('anonymous', 'What are you looking at right now?', 18),
  ('anonymous', 'Send the view from where you''re sitting', 19),
  ('anonymous', 'Confess something harmless 👀', 20),
  ('anonymous', 'Most overrated thing on campus?', 21),
  ('anonymous', 'Say the thing you''d never say out loud', 22),
  ('anonymous', 'What''s the plot twist of your week?', 23),
  ('anonymous', 'Unpopular opinion, go 🔥', 24),
  ('anonymous', 'Guess who this is 🎭', 25),
  ('anonymous', 'Rate this anonymously, be honest', 26),
  ('anonymous', 'Someone noticed. That''s all 🤍', 27),
  ('anonymous', 'You''re doing better than you think', 28),
  ('anonymous', 'This made someone''s day, quietly', 29),
  ('anonymous', 'Whatever it is, you''ll get through it', 30),
  ('anonymous', 'Genuinely, thank you for posting this', 31)
) as v(scope, prompt_text, sort_order)
where not exists (select 1 from public.ping_sheet_prompts);
