WITH src(parent, slot, kind, txt) AS (VALUES
 -- 1st Year
 ('Show the last thing you called home about.',1,'photo','Show me where you were standing on that call'),
 ('Show the last thing you called home about.',2,'text','Who did you call?'),
 ('Show the last thing you called home about.',3,'photo','Show me your call log'),
 ('Show the last thing you called home about.',4,'text','How often do you actually call?'),
 ('Show the last thing you called home about.',5,'photo','Show me something from home in your room'),
 ('Show the last thing you called home about.',6,'text','Be honest — did you tell them the full truth?'),

 ('Something you brought from home that you haven''t used once.',1,'photo','Show me where it''s been sitting'),
 ('Something you brought from home that you haven''t used once.',2,'text','Who packed it — you or them?'),
 ('Something you brought from home that you haven''t used once.',3,'photo','Show me it out of the bag'),
 ('Something you brought from home that you haven''t used once.',4,'text','Will you take it back in December?'),
 ('Something you brought from home that you haven''t used once.',5,'photo','Show me the thing from home you use daily'),
 ('Something you brought from home that you haven''t used once.',6,'text','Be honest — did you know you wouldn''t use it?'),

 ('The first friend you made here. Just their hands or shoes.',1,'photo','Show me where you met'),
 ('The first friend you made here. Just their hands or shoes.',2,'text','What was the first thing you said to each other?'),
 ('The first friend you made here. Just their hands or shoes.',3,'photo','Show me something you share now'),
 ('The first friend you made here. Just their hands or shoes.',4,'text','Are you still as close?'),
 ('The first friend you made here. Just their hands or shoes.',5,'photo','Show me your own shoes next to theirs'),
 ('The first friend you made here. Just their hands or shoes.',6,'text','Do they know they were the first?'),

 ('The senior advice that turned out to be a lie.',1,'photo','Show me the thing they lied about'),
 ('The senior advice that turned out to be a lie.',2,'text','What exactly did they say?'),
 ('The senior advice that turned out to be a lie.',3,'photo','Show me the reality of it'),
 ('The senior advice that turned out to be a lie.',4,'text','Did they mean well?'),
 ('The senior advice that turned out to be a lie.',5,'photo','Show me the advice that was actually true'),
 ('The senior advice that turned out to be a lie.',6,'text','Will you pass on the lie next year?'),

 ('The thing on campus you still can''t find.',1,'photo','Show me where you last looked'),
 ('The thing on campus you still can''t find.',2,'text','How many times have you tried?'),
 ('The thing on campus you still can''t find.',3,'photo','Show me the map or sign that confused you'),
 ('The thing on campus you still can''t find.',4,'text','Have you asked anyone?'),
 ('The thing on campus you still can''t find.',5,'photo','Show me where you are right now'),
 ('The thing on campus you still can''t find.',6,'text','Be honest — does it actually exist?'),

 ('What your hostel/desk looked like on day one vs. today.',1,'photo','Show me under the desk'),
 ('What your hostel/desk looked like on day one vs. today.',2,'text','What changed first?'),
 ('What your hostel/desk looked like on day one vs. today.',3,'photo','Show me the messiest corner'),
 ('What your hostel/desk looked like on day one vs. today.',4,'text','How long did day-one tidiness last?'),
 ('What your hostel/desk looked like on day one vs. today.',5,'photo','Show me your roommate''s side'),
 ('What your hostel/desk looked like on day one vs. today.',6,'text','Be honest — would your mum approve?'),

 ('Your first-week self vs. now — one photo that shows the difference.',1,'photo','Show me your first-week photo'),
 ('Your first-week self vs. now — one photo that shows the difference.',2,'text','What changed most, honestly?'),
 ('Your first-week self vs. now — one photo that shows the difference.',3,'photo','Show me what you wear now'),
 ('Your first-week self vs. now — one photo that shows the difference.',4,'text','What would first-week you think of you?'),
 ('Your first-week self vs. now — one photo that shows the difference.',5,'photo','Show me your face right now'),
 ('Your first-week self vs. now — one photo that shows the difference.',6,'text','Better or worse than you expected?'),

 ('Your timetable, annotated with how you actually feel.',1,'photo','Show me the worst day on it'),
 ('Your timetable, annotated with how you actually feel.',2,'text','Which class is the annotation about?'),
 ('Your timetable, annotated with how you actually feel.',3,'photo','Show me your 9 AM'),
 ('Your timetable, annotated with how you actually feel.',4,'text','How many 8 AMs have you actually made?'),
 ('Your timetable, annotated with how you actually feel.',5,'photo','Show me where you are during your free hour'),
 ('Your timetable, annotated with how you actually feel.',6,'text','Be honest — which class are you skipping tomorrow?'),

 -- 2nd Year
 ('Show the thing you finally learnt where everything is.',1,'photo','Show me the place you used to get lost'),
 ('Show the thing you finally learnt where everything is.',2,'text','How long did it take to figure out?'),
 ('Show the thing you finally learnt where everything is.',3,'photo','Show me the exact spot up close'),
 ('Show the thing you finally learnt where everything is.',4,'text','Who finally showed you?'),
 ('Show the thing you finally learnt where everything is.',5,'photo','Show me something you STILL haven''t figured out'),
 ('Show the thing you finally learnt where everything is.',6,'text','Be honest — did you ask or figure it out alone?'),

 ('Show what you spend your free hour on now.',1,'photo','Show me where you are while doing it'),
 ('Show what you spend your free hour on now.',2,'text','What did you spend it on in 1st year?'),
 ('Show what you spend your free hour on now.',3,'photo','Show me the thing itself, up close'),
 ('Show what you spend your free hour on now.',4,'text','How long has this been the routine?'),
 ('Show what you spend your free hour on now.',5,'photo','Show me someone else''s free hour'),
 ('Show what you spend your free hour on now.',6,'text','Be honest — is it actually productive?'),

 ('Something you own now that first-year you wouldn''t recognise.',1,'photo','Show me where you keep it'),
 ('Something you own now that first-year you wouldn''t recognise.',2,'text','When did you get it?'),
 ('Something you own now that first-year you wouldn''t recognise.',3,'photo','Show me it up close'),
 ('Something you own now that first-year you wouldn''t recognise.',4,'text','What would first-year you think of it?'),
 ('Something you own now that first-year you wouldn''t recognise.',5,'photo','Show me something first-year you WOULD recognise'),
 ('Something you own now that first-year you wouldn''t recognise.',6,'text','Be honest — did you need it or want it?'),

 ('Something you were scared of in first year that''s routine now.',1,'photo','Show me where it used to scare you'),
 ('Something you were scared of in first year that''s routine now.',2,'text','What actually changed?'),
 ('Something you were scared of in first year that''s routine now.',3,'photo','Show me yourself doing it now, easily'),
 ('Something you were scared of in first year that''s routine now.',4,'text','How long did the fear last?'),
 ('Something you were scared of in first year that''s routine now.',5,'photo','Show me something that still scares you'),
 ('Something you were scared of in first year that''s routine now.',6,'text','Be honest — would 1st-year you believe this?'),

 ('The first-year advice you''d actually give.',1,'photo','Show me where you''d give it'),
 ('The first-year advice you''d actually give.',2,'text','Did anyone give it to you?'),
 ('The first-year advice you''d actually give.',3,'photo','Show me proof it actually worked for you'),
 ('The first-year advice you''d actually give.',4,'text','How long did it take you to learn it?'),
 ('The first-year advice you''d actually give.',5,'photo','Show me the advice you''d ignore instead'),
 ('The first-year advice you''d actually give.',6,'text','Be honest — do you actually follow your own advice?'),

 ('The habit you picked up this year.',1,'photo','Show me it happening right now'),
 ('The habit you picked up this year.',2,'text','What started it?'),
 ('The habit you picked up this year.',3,'photo','Show me the exact thing up close'),
 ('The habit you picked up this year.',4,'text','How many days a week, honestly?'),
 ('The habit you picked up this year.',5,'photo','Show me a habit you dropped this year instead'),
 ('The habit you picked up this year.',6,'text','Be honest — is it a good habit or a bad one?'),

 ('Your current desk vs. your first-year desk. One photo.',1,'photo','Show me your first-year desk if you have it saved'),
 ('Your current desk vs. your first-year desk. One photo.',2,'text','What''s the biggest difference?'),
 ('Your current desk vs. your first-year desk. One photo.',3,'photo','Show me the messiest corner of it now'),
 ('Your current desk vs. your first-year desk. One photo.',4,'text','How long did it take to get this set up?'),
 ('Your current desk vs. your first-year desk. One photo.',5,'photo','Show me your roommate''s desk for comparison'),
 ('Your current desk vs. your first-year desk. One photo.',6,'text','Be honest — is it actually more organised now?'),

 ('Your timetable — show the gap you actually live in.',1,'photo','Show me where you are during that gap'),
 ('Your timetable — show the gap you actually live in.',2,'text','How long is the gap really?'),
 ('Your timetable — show the gap you actually live in.',3,'photo','Show me what you''re doing in it right now'),
 ('Your timetable — show the gap you actually live in.',4,'text','Is it enough time, honestly?'),
 ('Your timetable — show the gap you actually live in.',5,'photo','Show me someone else''s gap'),
 ('Your timetable — show the gap you actually live in.',6,'text','Be honest — do you waste most of it?'),

 -- 3rd Year
 ('Show the tab you keep reopening.',1,'photo','Show me the tab next to it'),
 ('Show the tab you keep reopening.',2,'text','How many times today?'),
 ('Show the tab you keep reopening.',3,'photo','Show me it up close'),
 ('Show the tab you keep reopening.',4,'text','Why do you keep closing it in the first place?'),
 ('Show the tab you keep reopening.',5,'photo','Show me a tab you finally closed for good'),
 ('Show the tab you keep reopening.',6,'text','Be honest — are you actually using it?'),

 ('Show what''s keeping you up lately.',1,'photo','Show me the room around you right now'),
 ('Show what''s keeping you up lately.',2,'text','How many hours of sleep is this costing you?'),
 ('Show what''s keeping you up lately.',3,'photo','Show me it up close'),
 ('Show what''s keeping you up lately.',4,'text','How long has this been going on?'),
 ('Show what''s keeping you up lately.',5,'photo','Show me what used to keep you up instead'),
 ('Show what''s keeping you up lately.',6,'text','Be honest — is it worth losing sleep over?'),

 ('Show where you work when it gets serious.',1,'photo','Show me what''s spread out around you'),
 ('Show where you work when it gets serious.',2,'text','How did you find this spot?'),
 ('Show where you work when it gets serious.',3,'photo','Show me the exact seat or corner'),
 ('Show where you work when it gets serious.',4,'text','How long can you actually focus here?'),
 ('Show where you work when it gets serious.',5,'photo','Show me where you work when it ISN''T serious'),
 ('Show where you work when it gets serious.',6,'text','Be honest — are you actually working right now?'),

 ('The project that''s eating this semester.',1,'photo','Show me the folder or files for it'),
 ('The project that''s eating this semester.',2,'text','How far behind are you, honestly?'),
 ('The project that''s eating this semester.',3,'photo','Show me the part that''s stuck'),
 ('The project that''s eating this semester.',4,'text','Who else is on it with you?'),
 ('The project that''s eating this semester.',5,'photo','Show me a project you''re glad is over'),
 ('The project that''s eating this semester.',6,'text','Be honest — will it be done on time?'),

 ('The thing you''re doing purely for placements.',1,'photo','Show me where you''re doing it right now'),
 ('The thing you''re doing purely for placements.',2,'text','Do you actually enjoy any of it?'),
 ('The thing you''re doing purely for placements.',3,'photo','Show me the proof or certificate for it'),
 ('The thing you''re doing purely for placements.',4,'text','How long have you been at this?'),
 ('The thing you''re doing purely for placements.',5,'photo','Show me something you do that has nothing to do with placements'),
 ('The thing you''re doing purely for placements.',6,'text','Be honest — is it actually working?'),

 ('Your calendar this week. Unedited.',1,'photo','Show me the busiest day on it'),
 ('Your calendar this week. Unedited.',2,'text','What''s the one thing you''re dreading?'),
 ('Your calendar this week. Unedited.',3,'photo','Show me today up close'),
 ('Your calendar this week. Unedited.',4,'text','Is any of this actually optional?'),
 ('Your calendar this week. Unedited.',5,'photo','Show me last week''s calendar for comparison'),
 ('Your calendar this week. Unedited.',6,'text','Be honest — will you get through all of it?'),

 ('Your prep setup, whatever stage it''s at.',1,'photo','Show me what''s spread around it'),
 ('Your prep setup, whatever stage it''s at.',2,'text','How far along are you, honestly?'),
 ('Your prep setup, whatever stage it''s at.',3,'photo','Show me the exact page or screen'),
 ('Your prep setup, whatever stage it''s at.',4,'text','How many hours a day right now?'),
 ('Your prep setup, whatever stage it''s at.',5,'photo','Show me someone else''s prep setup'),
 ('Your prep setup, whatever stage it''s at.',6,'text','Be honest — is it enough?'),

 ('Your resume on screen. Any version.',1,'photo','Show me the tab next to it'),
 ('Your resume on screen. Any version.',2,'text','How many versions exist right now?'),
 ('Your resume on screen. Any version.',3,'photo','Show me the line you''re least sure about'),
 ('Your resume on screen. Any version.',4,'text','Who last reviewed it?'),
 ('Your resume on screen. Any version.',5,'photo','Show me your very first resume ever'),
 ('Your resume on screen. Any version.',6,'text','Be honest — is everything on it true?'),

 -- 4th Year
 ('Show the place you''ve eaten at the most times.',1,'photo','Show me who you usually go with'),
 ('Show the place you''ve eaten at the most times.',2,'text','What''s your actual order there?'),
 ('Show the place you''ve eaten at the most times.',3,'photo','Show me the exact table or seat'),
 ('Show the place you''ve eaten at the most times.',4,'text','How many years has this been your place?'),
 ('Show the place you''ve eaten at the most times.',5,'photo','Show me the place you''re trying before you leave'),
 ('Show the place you''ve eaten at the most times.',6,'text','Be honest — do they know your order?'),

 ('Show what''s already packed.',1,'photo','Show me the room it''s packed in'),
 ('Show what''s already packed.',2,'text','Why this before anything else?'),
 ('Show what''s already packed.',3,'photo','Show me it up close'),
 ('Show what''s already packed.',4,'text','How early is too early to start packing?'),
 ('Show what''s already packed.',5,'photo','Show me what''s definitely not packed yet'),
 ('Show what''s already packed.',6,'text','Be honest — are you ready to leave?'),

 ('Show your desk in its final-year state.',1,'photo','Show me under it too'),
 ('Show your desk in its final-year state.',2,'text','What''s different from first year?'),
 ('Show your desk in its final-year state.',3,'photo','Show me the messiest corner'),
 ('Show your desk in its final-year state.',4,'text','What will happen to all of it?'),
 ('Show your desk in its final-year state.',5,'photo','Show me a 1st-year''s desk for comparison'),
 ('Show your desk in its final-year state.',6,'text','Be honest — will you miss this desk?'),

 ('Something you''ve carried since first year.',1,'photo','Show me where it''s been kept'),
 ('Something you''ve carried since first year.',2,'text','Why has it survived this long?'),
 ('Something you''ve carried since first year.',3,'photo','Show me it up close, worn and all'),
 ('Something you''ve carried since first year.',4,'text','Does it still work the way it used to?'),
 ('Something you''ve carried since first year.',5,'photo','Show me something you''ve already lost since then'),
 ('Something you''ve carried since first year.',6,'text','Be honest — are you taking it with you after?'),

 ('The spot on campus you''ll miss. Go stand there.',1,'photo','Show me the view from exactly there'),
 ('The spot on campus you''ll miss. Go stand there.',2,'text','What makes it the one you''ll miss?'),
 ('The spot on campus you''ll miss. Go stand there.',3,'photo','Show me the detail only you''d notice'),
 ('The spot on campus you''ll miss. Go stand there.',4,'text','How many years have you come here?'),
 ('The spot on campus you''ll miss. Go stand there.',5,'photo','Show me a spot you won''t miss at all'),
 ('The spot on campus you''ll miss. Go stand there.',6,'text','Be honest — will you actually come back to visit?'),

 ('The thing you still haven''t done here.',1,'photo','Show me where you''d do it'),
 ('The thing you still haven''t done here.',2,'text','What''s stopped you so far?'),
 ('The thing you still haven''t done here.',3,'photo','Show me how much time is left to do it'),
 ('The thing you still haven''t done here.',4,'text','Will you actually do it before you leave?'),
 ('The thing you still haven''t done here.',5,'photo','Show me something you DID manage to do'),
 ('The thing you still haven''t done here.',6,'text','Be honest — will you regret not doing it?'),

 ('Your last-ever timetable.',1,'photo','Show me the class you''ll miss most'),
 ('Your last-ever timetable.',2,'text','What does it feel like, seeing "last"?'),
 ('Your last-ever timetable.',3,'photo','Show me today''s slot up close'),
 ('Your last-ever timetable.',4,'text','How different is it from your first one?'),
 ('Your last-ever timetable.',5,'photo','Show me your very first timetable, if you kept it'),
 ('Your last-ever timetable.',6,'text','Be honest — are you ready for it to end?'),

 ('Your project/thesis, whatever it looks like right now.',1,'photo','Show me the desk it''s spread across'),
 ('Your project/thesis, whatever it looks like right now.',2,'text','How much is actually left?'),
 ('Your project/thesis, whatever it looks like right now.',3,'photo','Show me the page or section you''re stuck on'),
 ('Your project/thesis, whatever it looks like right now.',4,'text','Who''s guiding you through it?'),
 ('Your project/thesis, whatever it looks like right now.',5,'photo','Show me the very first draft you wrote'),
 ('Your project/thesis, whatever it looks like right now.',6,'text','Be honest — will it be done on time?'),

 -- Commute (Day Scholar / Day Scholar Commute)
 ('Show your route''s worst 10 seconds.',1,'photo','Show me what''s right before it'),
 ('Show your route''s worst 10 seconds.',2,'text','How long has it been this bad?'),
 ('Show your route''s worst 10 seconds.',3,'photo','Show me the exact spot up close'),
 ('Show your route''s worst 10 seconds.',4,'text','Is there actually no better way around it?'),
 ('Show your route''s worst 10 seconds.',5,'photo','Show me the best 10 seconds of your route instead'),
 ('Show your route''s worst 10 seconds.',6,'text','Be honest — do you dread this part every day?'),

 ('Something you eat on the way.',1,'photo','Show me where you got it'),
 ('Something you eat on the way.',2,'text','How often is this your breakfast?'),
 ('Something you eat on the way.',3,'photo','Show me it half-eaten'),
 ('Something you eat on the way.',4,'text','Do you always get the same thing?'),
 ('Something you eat on the way.',5,'photo','Show me what you''d eat if you had more time'),
 ('Something you eat on the way.',6,'text','Be honest — is this actually breakfast or just survival?'),

 ('The one thing that makes the commute worth it.',1,'photo','Show me it right now'),
 ('The one thing that makes the commute worth it.',2,'text','Would you commute without it?'),
 ('The one thing that makes the commute worth it.',3,'photo','Show me it up close'),
 ('The one thing that makes the commute worth it.',4,'text','How long have you relied on this?'),
 ('The one thing that makes the commute worth it.',5,'photo','Show me the part of the commute that ISN''T worth it'),
 ('The one thing that makes the commute worth it.',6,'text','Be honest — is it really enough some days?'),

 ('The seat you fight for.',1,'photo','Show me who else wants it'),
 ('The seat you fight for.',2,'text','How often do you actually get it?'),
 ('The seat you fight for.',3,'photo','Show me the seat itself, empty or not'),
 ('The seat you fight for.',4,'text','What makes it better than the rest?'),
 ('The seat you fight for.',5,'photo','Show me the seat you''re stuck with today'),
 ('The seat you fight for.',6,'text','Be honest — have you ever been rude about it?'),

 ('Traffic. Just traffic.',1,'photo','Show me what''s on either side of you'),
 ('Traffic. Just traffic.',2,'text','How long have you been stuck?'),
 ('Traffic. Just traffic.',3,'photo','Show me the vehicle right in front of you'),
 ('Traffic. Just traffic.',4,'text','Are you going to be late because of this?'),
 ('Traffic. Just traffic.',5,'photo','Show me a day this road was actually clear'),
 ('Traffic. Just traffic.',6,'text','Be honest — did you leave late again?'),

 ('What time you left home. Show the clock.',1,'photo','Show me the door you left through'),
 ('What time you left home. Show the clock.',2,'text','Was that earlier or later than usual?'),
 ('What time you left home. Show the clock.',3,'photo','Show me the exact time up close'),
 ('What time you left home. Show the clock.',4,'text','What made you leave at that time?'),
 ('What time you left home. Show the clock.',5,'photo','Show me the time you actually arrived'),
 ('What time you left home. Show the clock.',6,'text','Be honest — did you rush out the door?'),

 ('Your bag''s full weight, visualized.',1,'photo','Show me everything laid out from inside it'),
 ('Your bag''s full weight, visualized.',2,'text','How much of this did you actually need today?'),
 ('Your bag''s full weight, visualized.',3,'photo','Show me the heaviest single thing in it'),
 ('Your bag''s full weight, visualized.',4,'text','How far do you carry this every day?'),
 ('Your bag''s full weight, visualized.',5,'photo','Show me someone else''s bag for comparison'),
 ('Your bag''s full weight, visualized.',6,'text','Be honest — does your back actually hurt?'),

 ('Your view from the bus, right now.',1,'photo','Show me who''s sitting near you'),
 ('Your view from the bus, right now.',2,'text','How much longer till your stop?'),
 ('Your view from the bus, right now.',3,'photo','Show me what''s just passed the window'),
 ('Your view from the bus, right now.',4,'text','Is this the same view every day?'),
 ('Your view from the bus, right now.',5,'photo','Show me your view from yesterday for comparison'),
 ('Your view from the bus, right now.',6,'text','Be honest — are you actually paying attention to it?'),

 -- Hostel (Hostel / Hostel Life)
 ('Show what 2am in this building sounds like — one photo that captures it.',1,'photo','Show me the corridor right now'),
 ('Show what 2am in this building sounds like — one photo that captures it.',2,'text','Who''s the loudest on your floor?'),
 ('Show what 2am in this building sounds like — one photo that captures it.',3,'photo','Show me what''s making the noise'),
 ('Show what 2am in this building sounds like — one photo that captures it.',4,'text','What time does it actually go quiet?'),
 ('Show what 2am in this building sounds like — one photo that captures it.',5,'photo','Show me your earphones or earplugs'),
 ('Show what 2am in this building sounds like — one photo that captures it.',6,'text','Be honest — are you ever the noise?'),

 ('Something that''s been borrowed and never returned.',1,'photo','Show me the empty space where it was'),
 ('Something that''s been borrowed and never returned.',2,'text','Who has it?'),
 ('Something that''s been borrowed and never returned.',3,'photo','Show me something you''ve borrowed and not returned'),
 ('Something that''s been borrowed and never returned.',4,'text','How long ago?'),
 ('Something that''s been borrowed and never returned.',5,'photo','Show me what you replaced it with'),
 ('Something that''s been borrowed and never returned.',6,'text','Be honest — will you ever ask for it back?'),

 ('The jugaad you''re most proud of.',1,'photo','Show me it working'),
 ('The jugaad you''re most proud of.',2,'text','What was it supposed to be?'),
 ('The jugaad you''re most proud of.',3,'photo','Show me the parts you used'),
 ('The jugaad you''re most proud of.',4,'text','How long has it held?'),
 ('The jugaad you''re most proud of.',5,'photo','Show me the jugaad that failed'),
 ('The jugaad you''re most proud of.',6,'text','Would you do it the proper way if you could?'),

 ('The mess food tonight. Rate it in the caption.',1,'photo','Show me your plate after'),
 ('The mess food tonight. Rate it in the caption.',2,'text','What would make it a 10?'),
 ('The mess food tonight. Rate it in the caption.',3,'photo','Show me the one item that was actually good'),
 ('The mess food tonight. Rate it in the caption.',4,'text','What''s tomorrow''s menu?'),
 ('The mess food tonight. Rate it in the caption.',5,'photo','Show me your backup snack'),
 ('The mess food tonight. Rate it in the caption.',6,'text','Be honest — did you eat it or order?'),

 ('The wall above your bed.',1,'photo','Show me the wall opposite'),
 ('The wall above your bed.',2,'text','What''s the oldest thing up there?'),
 ('The wall above your bed.',3,'photo','Show me the thing you look at most'),
 ('The wall above your bed.',4,'text','What did you put up first?'),
 ('The wall above your bed.',5,'photo','Show me your roommate''s wall'),
 ('The wall above your bed.',6,'text','Be honest — is anything covering damage?'),

 ('What''s in your bucket.',1,'photo','Show me the bathroom situation'),
 ('What''s in your bucket.',2,'text','How long has that soap lasted?'),
 ('What''s in your bucket.',3,'photo','Show me your towel'),
 ('What''s in your bucket.',4,'text','What time do you shower?'),
 ('What''s in your bucket.',5,'photo','Show me your laundry pile'),
 ('What''s in your bucket.',6,'text','Be honest — when did you last wash the bucket?'),

 ('Your room right now. No warning, no cleaning.',1,'photo','Show me under the bed'),
 ('Your room right now. No warning, no cleaning.',2,'text','How long since it was properly clean?'),
 ('Your room right now. No warning, no cleaning.',3,'photo','Show me your desk surface'),
 ('Your room right now. No warning, no cleaning.',4,'text','Whose mess is worse, yours or theirs?'),
 ('Your room right now. No warning, no cleaning.',5,'photo','Show me the floor'),
 ('Your room right now. No warning, no cleaning.',6,'text','Be honest — did you move anything first?'),

 ('Your roommate''s side vs. your side.',1,'photo','Show me the exact dividing line'),
 ('Your roommate''s side vs. your side.',2,'text','Who''s messier, honestly?'),
 ('Your roommate''s side vs. your side.',3,'photo','Show me their desk'),
 ('Your roommate''s side vs. your side.',4,'text','Have you ever fought about it?'),
 ('Your roommate''s side vs. your side.',5,'photo','Show me the shared stuff'),
 ('Your roommate''s side vs. your side.',6,'text','Would they agree with your answer?'),

 -- Late Night Club
 ('Show what you''re eating at this hour.',1,'photo','Show me the room while you eat it'),
 ('Show what you''re eating at this hour.',2,'text','Is this your first meal since dinner?'),
 ('Show what you''re eating at this hour.',3,'photo','Show me it up close'),
 ('Show what you''re eating at this hour.',4,'text','How often is this a thing?'),
 ('Show what you''re eating at this hour.',5,'photo','Show me what you''d rather be eating'),
 ('Show what you''re eating at this hour.',6,'text','Be honest — should you be asleep instead?'),

 ('Show who else is still awake.',1,'photo','Show me what they''re doing'),
 ('Show who else is still awake.',2,'text','Are you actually talking, or just both awake?'),
 ('Show who else is still awake.',3,'photo','Show me your own setup right now'),
 ('Show who else is still awake.',4,'text','How often are you both up this late?'),
 ('Show who else is still awake.',5,'photo','Show me someone who''s already asleep'),
 ('Show who else is still awake.',6,'text','Be honest — will you regret this tomorrow?'),

 ('The tab you''re on at 2am.',1,'photo','Show me the tab before it'),
 ('The tab you''re on at 2am.',2,'text','Is this productive or just a spiral?'),
 ('The tab you''re on at 2am.',3,'photo','Show me it up close'),
 ('The tab you''re on at 2am.',4,'text','How long have you been on it?'),
 ('The tab you''re on at 2am.',5,'photo','Show me your tab from 2pm for comparison'),
 ('The tab you''re on at 2am.',6,'text','Be honest — are you going to close it now?'),

 ('The view out your window right now.',1,'photo','Show me the window itself'),
 ('The view out your window right now.',2,'text','How long have you been looking out?'),
 ('The view out your window right now.',3,'photo','Show me the one light still on nearby'),
 ('The view out your window right now.',4,'text','Is it different in daylight?'),
 ('The view out your window right now.',5,'photo','Show me your daytime view for comparison'),
 ('The view out your window right now.',6,'text','Be honest — should you be looking at a screen instead?'),

 ('What''s keeping you up. One photo.',1,'photo','Show me where you are right now'),
 ('What''s keeping you up. One photo.',2,'text','Is it something you can actually fix tonight?'),
 ('What''s keeping you up. One photo.',3,'photo','Show me it up close'),
 ('What''s keeping you up. One photo.',4,'text','How many nights has this happened?'),
 ('What''s keeping you up. One photo.',5,'photo','Show me what usually gets you to sleep'),
 ('What''s keeping you up. One photo.',6,'text','Be honest — will you actually sleep tonight?'),

 ('Your clock. Just the clock.',1,'photo','Show me the room around it'),
 ('Your clock. Just the clock.',2,'text','Should you already be asleep?'),
 ('Your clock. Just the clock.',3,'photo','Show me the exact time up close'),
 ('Your clock. Just the clock.',4,'text','What time did you plan to sleep by?'),
 ('Your clock. Just the clock.',5,'photo','Show me the clock from this time yesterday'),
 ('Your clock. Just the clock.',6,'text','Be honest — is this a pattern now?'),

 ('Your screen brightness right now.',1,'photo','Show me the room it''s lighting up'),
 ('Your screen brightness right now.',2,'text','Have you turned it down at all tonight?'),
 ('Your screen brightness right now.',3,'photo','Show me the slider itself'),
 ('Your screen brightness right now.',4,'text','How long have your eyes been on this screen?'),
 ('Your screen brightness right now.',5,'photo','Show me your screen time for today'),
 ('Your screen brightness right now.',6,'text','Be honest — do your eyes actually hurt?'),

 ('Your third coffee of the night.',1,'photo','Show me the first two cups, if they''re still around'),
 ('Your third coffee of the night.',2,'text','Are you going to regret this at 6am?'),
 ('Your third coffee of the night.',3,'photo','Show me it up close'),
 ('Your third coffee of the night.',4,'text','What are you actually trying to finish?'),
 ('Your third coffee of the night.',5,'photo','Show me your setup while drinking it'),
 ('Your third coffee of the night.',6,'text','Be honest — will there be a fourth?'),

 -- The orphaned global duplicate (same text, different row)
 ('What''s something you''ve never told anyone here?',1,'photo','Show me where you are right now'),
 ('What''s something you''ve never told anyone here?',2,'text','Why here, why now?'),
 ('What''s something you''ve never told anyone here?',3,'photo','Show me the thing closest to you'),
 ('What''s something you''ve never told anyone here?',4,'text','How long have you been carrying it?'),
 ('What''s something you''ve never told anyone here?',5,'photo','Show me your view'),
 ('What''s something you''ve never told anyone here?',6,'text','Does anyone at home know?')
)
INSERT INTO public.ping_prompts (prompt_text, daily_prompt_id, pool, prompt_kind, active, created_at)
SELECT s.txt, dp.id, 'linked', s.kind, true, now() + (s.slot * interval '1 millisecond')
FROM src s
JOIN public.daily_prompts dp ON dp.prompt_text = s.parent AND dp.active
WHERE NOT EXISTS (
  SELECT 1 FROM public.ping_prompts pp
   WHERE pp.daily_prompt_id = dp.id AND pp.prompt_text = s.txt
);
