WITH src(parent, slot, kind, txt) AS (VALUES
 -- Workshop (Aero/Chem/Civil/Mech)
 ('A structure on campus you have opinions about.',1,'photo','Show me it from the angle that bothers you most'),
 ('A structure on campus you have opinions about.',2,'text','What would you actually change about it?'),
 ('A structure on campus you have opinions about.',3,'photo','Show me the detail that gives it away'),
 ('A structure on campus you have opinions about.',4,'text','How long has it looked like this?'),
 ('A structure on campus you have opinions about.',5,'photo','Show me a structure you''d defend instead'),
 ('A structure on campus you have opinions about.',6,'text','Be honest — could you design better?'),

 ('Show a machine you''re not fully sure how to use.',1,'photo','Show me the manual, if there is one'),
 ('Show a machine you''re not fully sure how to use.',2,'text','Have you actually used it unsupervised?'),
 ('Show a machine you''re not fully sure how to use.',3,'photo','Show me the machine you do trust'),
 ('Show a machine you''re not fully sure how to use.',4,'text','Who showed you the wrong way first?'),
 ('Show a machine you''re not fully sure how to use.',5,'photo','Show me someone who actually knows it'),
 ('Show a machine you''re not fully sure how to use.',6,'text','Be honest — would you touch it alone right now?'),

 ('Something you made with your hands this semester.',1,'photo','Show me the raw material it started as'),
 ('Something you made with your hands this semester.',2,'text','What went wrong first try?'),
 ('Something you made with your hands this semester.',3,'photo','Show me it up close, flaws and all'),
 ('Something you made with your hands this semester.',4,'text','How many hours did it take?'),
 ('Something you made with your hands this semester.',5,'photo','Show me something someone else made'),
 ('Something you made with your hands this semester.',6,'text','Be honest — did you get full marks for it?'),

 ('The most over-engineered thing on campus.',1,'photo','Show me the simplest version it could''ve been'),
 ('The most over-engineered thing on campus.',2,'text','Who approved this, honestly?'),
 ('The most over-engineered thing on campus.',3,'photo','Show me the unnecessary part up close'),
 ('The most over-engineered thing on campus.',4,'text','How long has it been like this?'),
 ('The most over-engineered thing on campus.',5,'photo','Show me something under-engineered instead'),
 ('The most over-engineered thing on campus.',6,'text','Be honest — does it even work well?'),

 ('The workshop scar story — show the scar.',1,'photo','Show me the machine that did it'),
 ('The workshop scar story — show the scar.',2,'text','Did you tell anyone at the time?'),
 ('The workshop scar story — show the scar.',3,'photo','Show me the scar up close'),
 ('The workshop scar story — show the scar.',4,'text','How long ago did it happen?'),
 ('The workshop scar story — show the scar.',5,'photo','Show me someone else''s workshop scar'),
 ('The workshop scar story — show the scar.',6,'text','Be honest — was it your own fault?'),

 ('Your calculator. Yes, that one.',1,'photo','Show me the buttons that are worn off'),
 ('Your calculator. Yes, that one.',2,'text','How long have you owned it?'),
 ('Your calculator. Yes, that one.',3,'photo','Show me the back of it, stickers included'),
 ('Your calculator. Yes, that one.',4,'text','Has it ever nearly been lost?'),
 ('Your calculator. Yes, that one.',5,'photo','Show me someone else''s calculator'),
 ('Your calculator. Yes, that one.',6,'text','Be honest — do you know it better than your phone?'),

 ('Your drawing sheet. Be honest about the smudges.',1,'photo','Show me the corner you keep resting your hand on'),
 ('Your drawing sheet. Be honest about the smudges.',2,'text','How long did this one take?'),
 ('Your drawing sheet. Be honest about the smudges.',3,'photo','Show me the worst smudge up close'),
 ('Your drawing sheet. Be honest about the smudges.',4,'text','What tool made the mess?'),
 ('Your drawing sheet. Be honest about the smudges.',5,'photo','Show me someone else''s cleaner sheet'),
 ('Your drawing sheet. Be honest about the smudges.',6,'text','Be honest — will you resubmit this one?'),

 ('Your safety shoes after one lab.',1,'photo','Show me the floor of the lab itself'),
 ('Your safety shoes after one lab.',2,'text','What actually got on them?'),
 ('Your safety shoes after one lab.',3,'photo','Show me the soles up close'),
 ('Your safety shoes after one lab.',4,'text','How many labs have they survived?'),
 ('Your safety shoes after one lab.',5,'photo','Show me your normal shoes for comparison'),
 ('Your safety shoes after one lab.',6,'text','Be honest — do you clean them after?'),

 -- Software (AIML/CSE/ISE)
 ('Screenshot the last thing you Googled about a lab.',1,'photo','Show me the tab it was open next to'),
 ('Screenshot the last thing you Googled about a lab.',2,'text','Did it actually help?'),
 ('Screenshot the last thing you Googled about a lab.',3,'photo','Show me the lab manual for it'),
 ('Screenshot the last thing you Googled about a lab.',4,'text','How late were you working on it?'),
 ('Screenshot the last thing you Googled about a lab.',5,'photo','Show me your current tab'),
 ('Screenshot the last thing you Googled about a lab.',6,'text','Be honest — Stack Overflow or an AI?'),

 ('Show your setup. Cable chaos included.',1,'photo','Show me under the desk'),
 ('Show your setup. Cable chaos included.',2,'text','How long did it take to get to this state?'),
 ('Show your setup. Cable chaos included.',3,'photo','Show me your worst cable'),
 ('Show your setup. Cable chaos included.',4,'text','What would you upgrade first?'),
 ('Show your setup. Cable chaos included.',5,'photo','Show me your screen from where you sit'),
 ('Show your setup. Cable chaos included.',6,'text','Be honest — do you ever tidy it?'),

 ('Something you wrote that you don''t understand anymore.',1,'photo','Show me the file it''s in'),
 ('Something you wrote that you don''t understand anymore.',2,'text','How long ago did you write it?'),
 ('Something you wrote that you don''t understand anymore.',3,'photo','Show me the comments, if any'),
 ('Something you wrote that you don''t understand anymore.',4,'text','Does it still work?'),
 ('Something you wrote that you don''t understand anymore.',5,'photo','Show me code you''re proud of instead'),
 ('Something you wrote that you don''t understand anymore.',6,'text','Be honest — did you write it or paste it?'),

 ('The error message that''s been up the longest.',1,'photo','Show me the line it points to'),
 ('The error message that''s been up the longest.',2,'text','How long has it been there?'),
 ('The error message that''s been up the longest.',3,'photo','Show me the full stack trace'),
 ('The error message that''s been up the longest.',4,'text','What have you already tried?'),
 ('The error message that''s been up the longest.',5,'photo','Show me your terminal'),
 ('The error message that''s been up the longest.',6,'text','Be honest — do you know what it means?'),

 ('The line of code you''re weirdly proud of.',1,'photo','Show me the function it''s in'),
 ('The line of code you''re weirdly proud of.',2,'text','What does it actually do?'),
 ('The line of code you''re weirdly proud of.',3,'photo','Show me the version before it'),
 ('The line of code you''re weirdly proud of.',4,'text','How long did it take to get right?'),
 ('The line of code you''re weirdly proud of.',5,'photo','Show me your worst line in the same file'),
 ('The line of code you''re weirdly proud of.',6,'text','Would anyone else find it clever?'),

 ('Your code at 2am vs. your code at 2pm — one photo, you pick which.',1,'photo','Show me the other one'),
 ('Your code at 2am vs. your code at 2pm — one photo, you pick which.',2,'text','Which one is actually better?'),
 ('Your code at 2am vs. your code at 2pm — one photo, you pick which.',3,'photo','Show me your commit times'),
 ('Your code at 2am vs. your code at 2pm — one photo, you pick which.',4,'text','When do you do your real work?'),
 ('Your code at 2am vs. your code at 2pm — one photo, you pick which.',5,'photo','Show me your desk at that hour'),
 ('Your code at 2am vs. your code at 2pm — one photo, you pick which.',6,'text','Be honest — how late were you up?'),

 ('Your current tab situation.',1,'photo','Show me the tab you''ve had open longest'),
 ('Your current tab situation.',2,'text','How many are actually relevant?'),
 ('Your current tab situation.',3,'photo','Show me your bookmarks bar'),
 ('Your current tab situation.',4,'text','When did you last close them all?'),
 ('Your current tab situation.',5,'photo','Show me your other window'),
 ('Your current tab situation.',6,'text','Be honest — do you know what''s in tab 30?'),

 ('Your laptop stickers. Full frontal.',1,'photo','Show me the back or lid'),
 ('Your laptop stickers. Full frontal.',2,'text','Which one''s the oldest?'),
 ('Your laptop stickers. Full frontal.',3,'photo','Show me your favourite one close up'),
 ('Your laptop stickers. Full frontal.',4,'text','Where did you get most of them?'),
 ('Your laptop stickers. Full frontal.',5,'photo','Show me the laptop underneath, if there''s space'),
 ('Your laptop stickers. Full frontal.',6,'text','Be honest — any you regret?'),

 -- Biotech
 ('Show the machine you had to be trained on twice.',1,'photo','Show me the training sheet or badge'),
 ('Show the machine you had to be trained on twice.',2,'text','What went wrong the first time?'),
 ('Show the machine you had to be trained on twice.',3,'photo','Show me the exact control that confuses you'),
 ('Show the machine you had to be trained on twice.',4,'text','Who retrained you?'),
 ('Show the machine you had to be trained on twice.',5,'photo','Show me a machine you trust completely'),
 ('Show the machine you had to be trained on twice.',6,'text','Be honest — would you pass a test on it now?'),

 ('Show your gloves at the end of a session.',1,'photo','Show me the bench they were working on'),
 ('Show your gloves at the end of a session.',2,'text','What got on them?'),
 ('Show your gloves at the end of a session.',3,'photo','Show me the worst stain up close'),
 ('Show your gloves at the end of a session.',4,'text','How many pairs do you go through a week?'),
 ('Show your gloves at the end of a session.',5,'photo','Show me your hands right after taking them off'),
 ('Show your gloves at the end of a session.',6,'text','Be honest — did anything get through?'),

 ('Something growing that shouldn''t be.',1,'photo','Show me where you found it'),
 ('Something growing that shouldn''t be.',2,'text','How long has it been growing?'),
 ('Something growing that shouldn''t be.',3,'photo','Show me it up close'),
 ('Something growing that shouldn''t be.',4,'text','Is anyone going to deal with it?'),
 ('Something growing that shouldn''t be.',5,'photo','Show me something growing on purpose instead'),
 ('Something growing that shouldn''t be.',6,'text','Be honest — is it a little bit fascinating?'),

 ('The plate/slide you''re waiting on.',1,'photo','Show me the incubator or scope it''s in'),
 ('The plate/slide you''re waiting on.',2,'text','How much longer till results?'),
 ('The plate/slide you''re waiting on.',3,'photo','Show me it up close right now'),
 ('The plate/slide you''re waiting on.',4,'text','What happens if it fails?'),
 ('The plate/slide you''re waiting on.',5,'photo','Show me a plate that already worked'),
 ('The plate/slide you''re waiting on.',6,'text','Be honest — are you nervous about it?'),

 ('Whatever''s in front of you on the bench.',1,'photo','Show me the rest of the bench'),
 ('Whatever''s in front of you on the bench.',2,'text','What are you actually doing with it?'),
 ('Whatever''s in front of you on the bench.',3,'photo','Show me it up close'),
 ('Whatever''s in front of you on the bench.',4,'text','How long have you been at this bench today?'),
 ('Whatever''s in front of you on the bench.',5,'photo','Show me someone else''s bench'),
 ('Whatever''s in front of you on the bench.',6,'text','Be honest — do you know what you''re doing?'),

 ('Your goggles, wherever they''re sitting.',1,'photo','Show me the room they''re sitting in'),
 ('Your goggles, wherever they''re sitting.',2,'text','How scratched are the lenses, honestly?'),
 ('Your goggles, wherever they''re sitting.',3,'photo','Show me the lenses up close'),
 ('Your goggles, wherever they''re sitting.',4,'text','How long have you had this pair?'),
 ('Your goggles, wherever they''re sitting.',5,'photo','Show me someone else wearing theirs'),
 ('Your goggles, wherever they''re sitting.',6,'text','Be honest — do you always wear them?'),

 ('Your lab coat. Be honest about the stains.',1,'photo','Show me the pocket you actually use'),
 ('Your lab coat. Be honest about the stains.',2,'text','What made the worst stain?'),
 ('Your lab coat. Be honest about the stains.',3,'photo','Show me the worst stain up close'),
 ('Your lab coat. Be honest about the stains.',4,'text','How often does it get washed?'),
 ('Your lab coat. Be honest about the stains.',5,'photo','Show me a coat that''s spotless'),
 ('Your lab coat. Be honest about the stains.',6,'text','Be honest — do you know what every stain is?'),

 ('Your lab notebook''s messiest entry.',1,'photo','Show me the page before it'),
 ('Your lab notebook''s messiest entry.',2,'text','Can you actually read your own writing here?'),
 ('Your lab notebook''s messiest entry.',3,'photo','Show me the messiest line up close'),
 ('Your lab notebook''s messiest entry.',4,'text','What happened that day?'),
 ('Your lab notebook''s messiest entry.',5,'photo','Show me your neatest entry instead'),
 ('Your lab notebook''s messiest entry.',6,'text','Be honest — will this pass an audit?'),

 -- Electronics (ECE/EEE/EIE)
 ('Show your component drawer or box.',1,'photo','Show me the compartment that''s a mess'),
 ('Show your component drawer or box.',2,'text','How many of these do you actually use?'),
 ('Show your component drawer or box.',3,'photo','Show me the oldest component in it'),
 ('Show your component drawer or box.',4,'text','How long have you been collecting these?'),
 ('Show your component drawer or box.',5,'photo','Show me someone else''s box'),
 ('Show your component drawer or box.',6,'text','Be honest — do you know what half of these do?'),

 ('Show your lab record''s worst page.',1,'photo','Show me the page it should''ve looked like'),
 ('Show your lab record''s worst page.',2,'text','What went wrong that day?'),
 ('Show your lab record''s worst page.',3,'photo','Show me the correction marks up close'),
 ('Show your lab record''s worst page.',4,'text','Did you get marked down for it?'),
 ('Show your lab record''s worst page.',5,'photo','Show me your best page instead'),
 ('Show your lab record''s worst page.',6,'text','Be honest — did you copy any of this?'),

 ('The circuit that worked once and never again.',1,'photo','Show me it as it sits now'),
 ('The circuit that worked once and never again.',2,'text','What did you change right before it died?'),
 ('The circuit that worked once and never again.',3,'photo','Show me the connection you suspect'),
 ('The circuit that worked once and never again.',4,'text','How long have you tried to fix it?'),
 ('The circuit that worked once and never again.',5,'photo','Show me a circuit that''s never failed you'),
 ('The circuit that worked once and never again.',6,'text','Be honest — have you given up on it?'),

 ('The component you''ve burnt the most of.',1,'photo','Show me the pile of dead ones'),
 ('The component you''ve burnt the most of.',2,'text','What''s the usual cause?'),
 ('The component you''ve burnt the most of.',3,'photo','Show me one up close, burnt marks and all'),
 ('The component you''ve burnt the most of.',4,'text','How many have you gone through this semester?'),
 ('The component you''ve burnt the most of.',5,'photo','Show me the component you''ve never damaged'),
 ('The component you''ve burnt the most of.',6,'text','Be honest — do you check the datasheet first?'),

 ('The soldering iron burn. Everyone has one.',1,'photo','Show me the iron that did it'),
 ('The soldering iron burn. Everyone has one.',2,'text','Did you finish the joint anyway?'),
 ('The soldering iron burn. Everyone has one.',3,'photo','Show me the burn up close'),
 ('The soldering iron burn. Everyone has one.',4,'text','How long ago did it happen?'),
 ('The soldering iron burn. Everyone has one.',5,'photo','Show me someone else''s burn'),
 ('The soldering iron burn. Everyone has one.',6,'text','Be honest — were you rushing?'),

 ('Your breadboard. Current state, wires and all.',1,'photo','Show me the rest of the bench it''s sitting on'),
 ('Your breadboard. Current state, wires and all.',2,'text','Does it actually work right now?'),
 ('Your breadboard. Current state, wires and all.',3,'photo','Show me the messiest corner of that breadboard'),
 ('Your breadboard. Current state, wires and all.',4,'text','How long has it been wired like that?'),
 ('Your breadboard. Current state, wires and all.',5,'photo','Show me the same circuit on paper'),
 ('Your breadboard. Current state, wires and all.',6,'text','Be honest — could you rebuild it from scratch?'),

 ('Your multimeter reading right now. Any reading.',1,'photo','Show me what it''s connected to'),
 ('Your multimeter reading right now. Any reading.',2,'text','Is that the reading you expected?'),
 ('Your multimeter reading right now. Any reading.',3,'photo','Show me the display up close'),
 ('Your multimeter reading right now. Any reading.',4,'text','How old is this multimeter?'),
 ('Your multimeter reading right now. Any reading.',5,'photo','Show me a reading that surprised you before'),
 ('Your multimeter reading right now. Any reading.',6,'text','Be honest — do you trust this one fully?'),

 ('Your oscilloscope screen, whatever''s on it.',1,'photo','Show me the probes attached to it'),
 ('Your oscilloscope screen, whatever''s on it.',2,'text','Is this the waveform you wanted?'),
 ('Your oscilloscope screen, whatever''s on it.',3,'photo','Show me the screen up close'),
 ('Your oscilloscope screen, whatever''s on it.',4,'text','How long have you been staring at this?'),
 ('Your oscilloscope screen, whatever''s on it.',5,'photo','Show me a waveform that actually made sense'),
 ('Your oscilloscope screen, whatever''s on it.',6,'text','Be honest — do you fully understand this one?'),

 -- IEM
 ('Show something here that''s badly queued.',1,'photo','Show me the queue in full'),
 ('Show something here that''s badly queued.',2,'text','How would you actually fix it?'),
 ('Show something here that''s badly queued.',3,'photo','Show me the bottleneck up close'),
 ('Show something here that''s badly queued.',4,'text','How long has it been this bad?'),
 ('Show something here that''s badly queued.',5,'photo','Show me a queue that works well'),
 ('Show something here that''s badly queued.',6,'text','Be honest — has anyone complained yet?'),

 ('Show the process on campus you''d optimise first.',1,'photo','Show me it happening right now'),
 ('Show the process on campus you''d optimise first.',2,'text','What''s your actual fix?'),
 ('Show the process on campus you''d optimise first.',3,'photo','Show me the exact step that wastes time'),
 ('Show the process on campus you''d optimise first.',4,'text','How much time would your fix save?'),
 ('Show the process on campus you''d optimise first.',5,'photo','Show me a process that already works well'),
 ('Show the process on campus you''d optimise first.',6,'text','Be honest — would anyone actually adopt your fix?'),

 ('Show your notes from the last group project meeting.',1,'photo','Show me who else was in the meeting'),
 ('Show your notes from the last group project meeting.',2,'text','Did the meeting actually decide anything?'),
 ('Show your notes from the last group project meeting.',3,'photo','Show me the messiest part of the notes'),
 ('Show your notes from the last group project meeting.',4,'text','How long did the meeting run over?'),
 ('Show your notes from the last group project meeting.',5,'photo','Show me someone else''s notes from it'),
 ('Show your notes from the last group project meeting.',6,'text','Be honest — did you zone out at any point?'),

 ('The chart you''re weirdly proud of.',1,'photo','Show me the raw data behind it'),
 ('The chart you''re weirdly proud of.',2,'text','What does it actually prove?'),
 ('The chart you''re weirdly proud of.',3,'photo','Show me the axis labels up close'),
 ('The chart you''re weirdly proud of.',4,'text','How long did it take to make?'),
 ('The chart you''re weirdly proud of.',5,'photo','Show me a chart you''re embarrassed by'),
 ('The chart you''re weirdly proud of.',6,'text','Would anyone else find it clever?'),

 ('The deadline on your wall or screen.',1,'photo','Show me what''s around it'),
 ('The deadline on your wall or screen.',2,'text','Are you actually going to make it?'),
 ('The deadline on your wall or screen.',3,'photo','Show me the date up close'),
 ('The deadline on your wall or screen.',4,'text','How long have you known about it?'),
 ('The deadline on your wall or screen.',5,'photo','Show me a deadline you already missed'),
 ('The deadline on your wall or screen.',6,'text','Be honest — have you started yet?'),

 ('The spreadsheet you''re in right now.',1,'photo','Show me the tab you''re actually working on'),
 ('The spreadsheet you''re in right now.',2,'text','What''s it actually for?'),
 ('The spreadsheet you''re in right now.',3,'photo','Show me the formula you''re proudest of'),
 ('The spreadsheet you''re in right now.',4,'text','How long has this sheet existed?'),
 ('The spreadsheet you''re in right now.',5,'photo','Show me someone else''s version of it'),
 ('The spreadsheet you''re in right now.',6,'text','Be honest — is it actually accurate?'),

 ('Your calculator or laptop, whichever you use more.',1,'photo','Show me the one you didn''t pick'),
 ('Your calculator or laptop, whichever you use more.',2,'text','Why that one over the other?'),
 ('Your calculator or laptop, whichever you use more.',3,'photo','Show me it up close, wear and all'),
 ('Your calculator or laptop, whichever you use more.',4,'text','How long have you had it?'),
 ('Your calculator or laptop, whichever you use more.',5,'photo','Show me someone using the other one'),
 ('Your calculator or laptop, whichever you use more.',6,'text','Be honest — could you survive without it for a day?'),

 ('Your team''s actual workload split, visualized however you want.',1,'photo','Show me the tool you used to visualize it'),
 ('Your team''s actual workload split, visualized however you want.',2,'text','Is the split actually fair?'),
 ('Your team''s actual workload split, visualized however you want.',3,'photo','Show me your own slice up close'),
 ('Your team''s actual workload split, visualized however you want.',4,'text','Who''s carrying the most right now?'),
 ('Your team''s actual workload split, visualized however you want.',5,'photo','Show me a past project''s split for comparison'),
 ('Your team''s actual workload split, visualized however you want.',6,'text','Be honest — would your team agree with this chart?'),

 -- Tech: AI & ML / Coding-DSA
 ('Show a wire/board/device you''re building.',1,'photo','Show me the mess of parts around it'),
 ('Show a wire/board/device you''re building.',2,'text','Does it actually do anything yet?'),
 ('Show a wire/board/device you''re building.',3,'photo','Show me the connection you''re least sure about'),
 ('Show a wire/board/device you''re building.',4,'text','How long have you been building it?'),
 ('Show a wire/board/device you''re building.',5,'photo','Show me a build you''re done with'),
 ('Show a wire/board/device you''re building.',6,'text','Be honest — do you know why it isn''t working?'),

 ('Show the project you abandoned.',1,'photo','Show me where it''s sitting now'),
 ('Show the project you abandoned.',2,'text','What made you stop?'),
 ('Show the project you abandoned.',3,'photo','Show me the last commit or file'),
 ('Show the project you abandoned.',4,'text','How far did you actually get?'),
 ('Show the project you abandoned.',5,'photo','Show me the project you''re actually finishing'),
 ('Show the project you abandoned.',6,'text','Be honest — will you ever come back to it?'),

 ('The number of unread notifications on your dev tools.',1,'photo','Show me the exact badge count'),
 ('The number of unread notifications on your dev tools.',2,'text','How long has it been building up?'),
 ('The number of unread notifications on your dev tools.',3,'photo','Show me the oldest one still there'),
 ('The number of unread notifications on your dev tools.',4,'text','Are any of these actually urgent?'),
 ('The number of unread notifications on your dev tools.',5,'photo','Show me your phone''s badge count too'),
 ('The number of unread notifications on your dev tools.',6,'text','Be honest — will you clear it today?'),

 ('The wildest bug you''ve hit this week.',1,'photo','Show me the error it threw'),
 ('The wildest bug you''ve hit this week.',2,'text','How long did it take to find?'),
 ('The wildest bug you''ve hit this week.',3,'photo','Show me the exact line that caused it'),
 ('The wildest bug you''ve hit this week.',4,'text','What was actually causing it?'),
 ('The wildest bug you''ve hit this week.',5,'photo','Show me the fix, if you have one'),
 ('The wildest bug you''ve hit this week.',6,'text','Be honest — did you cry a little?'),

 ('Your GitHub contribution graph. No excuses.',1,'photo','Show me your busiest week on it'),
 ('Your GitHub contribution graph. No excuses.',2,'text','What''s the real reason for the gaps?'),
 ('Your GitHub contribution graph. No excuses.',3,'photo','Show me the emptiest stretch up close'),
 ('Your GitHub contribution graph. No excuses.',4,'text','How long is your current streak?'),
 ('Your GitHub contribution graph. No excuses.',5,'photo','Show me someone else''s graph'),
 ('Your GitHub contribution graph. No excuses.',6,'text','Be honest — do any commits say "fix"?'),

 ('Your most-used keyboard shortcut, demonstrated.',1,'photo','Show me the rest of your keyboard'),
 ('Your most-used keyboard shortcut, demonstrated.',2,'text','How did you learn it?'),
 ('Your most-used keyboard shortcut, demonstrated.',3,'photo','Show me the keys up close'),
 ('Your most-used keyboard shortcut, demonstrated.',4,'text','How many times a day do you hit it?'),
 ('Your most-used keyboard shortcut, demonstrated.',5,'photo','Show me a shortcut you still don''t know'),
 ('Your most-used keyboard shortcut, demonstrated.',6,'text','Be honest — could you code without it now?'),

 ('Your rubber duck (or whatever you talk to).',1,'photo','Show me where it usually sits'),
 ('Your rubber duck (or whatever you talk to).',2,'text','Does talking to it actually help?'),
 ('Your rubber duck (or whatever you talk to).',3,'photo','Show me it up close'),
 ('Your rubber duck (or whatever you talk to).',4,'text','How long have you had this habit?'),
 ('Your rubber duck (or whatever you talk to).',5,'photo','Show me who you talk to when it doesn''t help'),
 ('Your rubber duck (or whatever you talk to).',6,'text','Be honest — do you feel silly doing it?'),

 ('Your terminal. Whatever''s on it.',1,'photo','Show me the window behind it'),
 ('Your terminal. Whatever''s on it.',2,'text','What are you actually running right now?'),
 ('Your terminal. Whatever''s on it.',3,'photo','Show me the last command you typed'),
 ('Your terminal. Whatever''s on it.',4,'text','How long has this session been open?'),
 ('Your terminal. Whatever''s on it.',5,'photo','Show me your theme or colour scheme choice'),
 ('Your terminal. Whatever''s on it.',6,'text','Be honest — do you know every alias in there?')
)
INSERT INTO public.ping_prompts (prompt_text, daily_prompt_id, pool, prompt_kind, active, created_at)
SELECT s.txt, dp.id, 'linked', s.kind, true, now() + (s.slot * interval '1 millisecond')
FROM src s
JOIN public.daily_prompts dp ON dp.prompt_text = s.parent AND dp.active
WHERE NOT EXISTS (
  SELECT 1 FROM public.ping_prompts pp
   WHERE pp.daily_prompt_id = dp.id AND pp.prompt_text = s.txt
);
