WITH src(parent, slot, kind, txt) AS (VALUES
 ('OVERRRATED COLLEGE PLACE',1,'photo','Show me the place itself, right now'),
 ('OVERRRATED COLLEGE PLACE',2,'text','What do people expect vs. what they get there?'),
 ('OVERRRATED COLLEGE PLACE',3,'photo','Show me the detail that gives it away'),
 ('OVERRRATED COLLEGE PLACE',4,'text','Did it affect your choice to come here?'),
 ('OVERRRATED COLLEGE PLACE',5,'photo','Show me the most underrated place instead'),
 ('OVERRRATED COLLEGE PLACE',6,'text','Be honest — do you still go there anyway?'),

 ('Show me your notes from the last prep session.',1,'photo','Show me who else was in the session'),
 ('Show me your notes from the last prep session.',2,'text','Did it actually help?'),
 ('Show me your notes from the last prep session.',3,'photo','Show me the messiest part of the notes'),
 ('Show me your notes from the last prep session.',4,'text','How long was the session?'),
 ('Show me your notes from the last prep session.',5,'photo','Show me your very first prep notes ever'),
 ('Show me your notes from the last prep session.',6,'text','Be honest — did you zone out at any point?'),

 ('Show what you''re building.',1,'photo','Show me the mess of parts or tabs around it'),
 ('Show what you''re building.',2,'text','Does it actually work yet?'),
 ('Show what you''re building.',3,'photo','Show me the part you''re stuck on'),
 ('Show what you''re building.',4,'text','How long have you been building it?'),
 ('Show what you''re building.',5,'photo','Show me something you finished building before'),
 ('Show what you''re building.',6,'text','Be honest — will you actually ship it?'),

 ('Show your 3am work session.',1,'photo','Show me the room around you'),
 ('Show your 3am work session.',2,'text','What are you actually trying to finish?'),
 ('Show your 3am work session.',3,'photo','Show me your screen up close'),
 ('Show your 3am work session.',4,'text','How many hours have you been at it?'),
 ('Show your 3am work session.',5,'photo','Show me your desk in daylight for comparison'),
 ('Show your 3am work session.',6,'text','Be honest — could this have waited till morning?'),

 ('The company sticker on your laptop.',1,'photo','Show me the rest of the lid'),
 ('The company sticker on your laptop.',2,'text','How did you get it?'),
 ('The company sticker on your laptop.',3,'photo','Show me it up close'),
 ('The company sticker on your laptop.',4,'text','Is it a company you actually want to join?'),
 ('The company sticker on your laptop.',5,'photo','Show me a sticker you regret putting on'),
 ('The company sticker on your laptop.',6,'text','Be honest — did you earn it or just attend an event?'),

 ('The whiteboard/notebook where the idea started.',1,'photo','Show me where it''s sitting now'),
 ('The whiteboard/notebook where the idea started.',2,'text','Who else was there when it started?'),
 ('The whiteboard/notebook where the idea started.',3,'photo','Show me the exact sketch or line'),
 ('The whiteboard/notebook where the idea started.',4,'text','How far has the idea actually gone since?'),
 ('The whiteboard/notebook where the idea started.',5,'photo','Show me where the idea stands today'),
 ('The whiteboard/notebook where the idea started.',6,'text','Be honest — do you still believe in it?'),

 ('Your LinkedIn photo vs. your actual face right now.',1,'photo','Show me your actual face right now'),
 ('Your LinkedIn photo vs. your actual face right now.',2,'text','How long ago was the LinkedIn photo taken?'),
 ('Your LinkedIn photo vs. your actual face right now.',3,'photo','Show me the LinkedIn photo up close'),
 ('Your LinkedIn photo vs. your actual face right now.',4,'text','Who took it, or did you do it yourself?'),
 ('Your LinkedIn photo vs. your actual face right now.',5,'photo','Show me your very first LinkedIn photo ever'),
 ('Your LinkedIn photo vs. your actual face right now.',6,'text','Be honest — is it time for an update?'),

 ('Your rejection count. Just the number.',1,'photo','Show me one of the actual rejection emails'),
 ('Your rejection count. Just the number.',2,'text','Which one stung the most?'),
 ('Your rejection count. Just the number.',3,'photo','Show me the number up close'),
 ('Your rejection count. Just the number.',4,'text','How long have you been applying?'),
 ('Your rejection count. Just the number.',5,'photo','Show me the one offer that made up for it, if you have it'),
 ('Your rejection count. Just the number.',6,'text','Be honest — did any of them actually hurt?'),

 ('Your resume''s current version number.',1,'photo','Show me the resume open on screen'),
 ('Your resume''s current version number.',2,'text','What changed since the last version?'),
 ('Your resume''s current version number.',3,'photo','Show me the file name up close'),
 ('Your resume''s current version number.',4,'text','Who last reviewed this version?'),
 ('Your resume''s current version number.',5,'photo','Show me your very first version ever'),
 ('Your resume''s current version number.',6,'text','Be honest — is everything on it still true?'),

 ('A photo you took that nobody liked but you love.',1,'photo','Show me it again, full-screen'),
 ('A photo you took that nobody liked but you love.',2,'text','What do you see in it that they don''t?'),
 ('A photo you took that nobody liked but you love.',3,'photo','Show me the detail you love most'),
 ('A photo you took that nobody liked but you love.',4,'text','How many likes did it actually get?'),
 ('A photo you took that nobody liked but you love.',5,'photo','Show me the photo that got the most likes instead'),
 ('A photo you took that nobody liked but you love.',6,'text','Be honest — will you post something like it again?'),

 ('Show something ordinary made to look expensive.',1,'photo','Show me the actual ordinary object'),
 ('Show something ordinary made to look expensive.',2,'text','What''s the actual trick you used?'),
 ('Show something ordinary made to look expensive.',3,'photo','Show me the setup around it'),
 ('Show something ordinary made to look expensive.',4,'text','How long did the shot take to set up?'),
 ('Show something ordinary made to look expensive.',5,'photo','Show me a shot that failed to look expensive'),
 ('Show something ordinary made to look expensive.',6,'text','Be honest — did anyone believe it was real?'),

 ('Show your gear, however humble.',1,'photo','Show me the bag it all fits in'),
 ('Show your gear, however humble.',2,'text','What''s the one piece you''d upgrade first?'),
 ('Show your gear, however humble.',3,'photo','Show me the piece you use most'),
 ('Show your gear, however humble.',4,'text','How long have you had this setup?'),
 ('Show your gear, however humble.',5,'photo','Show me the gear you wish you had'),
 ('Show your gear, however humble.',6,'text','Be honest — does the gear actually matter that much?'),

 ('The best light on campus right now. Go find it.',1,'photo','Show me what''s being lit by it'),
 ('The best light on campus right now. Go find it.',2,'text','How did you know to look there?'),
 ('The best light on campus right now. Go find it.',3,'photo','Show me the light itself, close up'),
 ('The best light on campus right now. Go find it.',4,'text','How long will this light last today?'),
 ('The best light on campus right now. Go find it.',5,'photo','Show me the worst light on campus for comparison'),
 ('The best light on campus right now. Go find it.',6,'text','Be honest — did you have to run to catch it?'),

 ('The same spot you always shoot, shot again.',1,'photo','Show me an old shot of the same spot'),
 ('The same spot you always shoot, shot again.',2,'text','What''s different about it today?'),
 ('The same spot you always shoot, shot again.',3,'photo','Show me the detail you focused on this time'),
 ('The same spot you always shoot, shot again.',4,'text','How many times have you shot this spot?'),
 ('The same spot you always shoot, shot again.',5,'photo','Show me a spot you''ve never shot before'),
 ('The same spot you always shoot, shot again.',6,'text','Be honest — are you bored of this spot yet?'),

 ('Your camera roll''s most recent photo. No choosing.',1,'photo','Show me the photo right before it'),
 ('Your camera roll''s most recent photo. No choosing.',2,'text','Was it intentional or an accident?'),
 ('Your camera roll''s most recent photo. No choosing.',3,'photo','Show me it up close'),
 ('Your camera roll''s most recent photo. No choosing.',4,'text','How many minutes ago was it taken?'),
 ('Your camera roll''s most recent photo. No choosing.',5,'photo','Show me your favourite photo from today instead'),
 ('Your camera roll''s most recent photo. No choosing.',6,'text','Be honest — are you going to delete it?'),

 ('Your editing screen mid-edit.',1,'photo','Show me the original, unedited'),
 ('Your editing screen mid-edit.',2,'text','What are you actually fixing right now?'),
 ('Your editing screen mid-edit.',3,'photo','Show me the slider or tool you use most'),
 ('Your editing screen mid-edit.',4,'text','How long does an edit usually take you?'),
 ('Your editing screen mid-edit.',5,'photo','Show me the final result, if it''s done'),
 ('Your editing screen mid-edit.',6,'text','Be honest — did you overdo it a little?'),

 ('Your worst photo from a good day.',1,'photo','Show me the best photo from the same day'),
 ('Your worst photo from a good day.',2,'text','Why did you even keep it?'),
 ('Your worst photo from a good day.',3,'photo','Show me the exact flaw up close'),
 ('Your worst photo from a good day.',4,'text','What went wrong when you took it?'),
 ('Your worst photo from a good day.',5,'photo','Show me your worst photo ever, any day'),
 ('Your worst photo from a good day.',6,'text','Be honest — would you delete it if asked?'),

 ('Show the notice board nobody reads.',1,'photo','Show me what''s actually pinned on it'),
 ('Show the notice board nobody reads.',2,'text','When was the last thing updated?'),
 ('Show the notice board nobody reads.',3,'photo','Show me the oldest notice on it'),
 ('Show the notice board nobody reads.',4,'text','Have you ever read one?'),
 ('Show the notice board nobody reads.',5,'photo','Show me the board people DO read'),
 ('Show the notice board nobody reads.',6,'text','What should be on it instead?'),

 ('Show what the parking looks like at this hour.',1,'photo','Show me your own vehicle in it'),
 ('Show what the parking looks like at this hour.',2,'text','How long did it take to find a spot?'),
 ('Show what the parking looks like at this hour.',3,'photo','Show me the worst-parked one'),
 ('Show what the parking looks like at this hour.',4,'text','What time do you have to arrive to get a spot?'),
 ('Show what the parking looks like at this hour.',5,'photo','Show me the exit queue'),
 ('Show what the parking looks like at this hour.',6,'text','Be honest — have you parked badly too?'),

 ('Something here that''s been broken the entire time you''ve been on campus.',1,'photo','Show me it closer'),
 ('Something here that''s been broken the entire time you''ve been on campus.',2,'text','How long is "the entire time" for you?'),
 ('Something here that''s been broken the entire time you''ve been on campus.',3,'photo','Show me what''s next to it'),
 ('Something here that''s been broken the entire time you''ve been on campus.',4,'text','Has anyone reported it?'),
 ('Something here that''s been broken the entire time you''ve been on campus.',5,'photo','Show me something here that works perfectly'),
 ('Something here that''s been broken the entire time you''ve been on campus.',6,'text','What would it cost to fix, honestly?'),

 ('The building you still take a wrong turn in.',1,'photo','Show me the exact turn you get wrong'),
 ('The building you still take a wrong turn in.',2,'text','How many times have you done it?'),
 ('The building you still take a wrong turn in.',3,'photo','Show me the floor plan or sign, if any'),
 ('The building you still take a wrong turn in.',4,'text','Which floor is it?'),
 ('The building you still take a wrong turn in.',5,'photo','Show me the building you know perfectly'),
 ('The building you still take a wrong turn in.',6,'text','Be honest — do you still use maps on campus?'),

 ('The one bench everyone fights for.',1,'photo','Show me who''s on it right now'),
 ('The one bench everyone fights for.',2,'text','What makes it better than the others?'),
 ('The one bench everyone fights for.',3,'photo','Show me the bench nobody wants'),
 ('The one bench everyone fights for.',4,'text','Have you ever got it?'),
 ('The one bench everyone fights for.',5,'photo','Show me where you''re sitting instead'),
 ('The one bench everyone fights for.',6,'text','Be honest — would you save it for a friend?'),

 ('The queue you''re standing in right now.',1,'photo','Show me the front of it'),
 ('The queue you''re standing in right now.',2,'text','How long have you been waiting?'),
 ('The queue you''re standing in right now.',3,'photo','Show me what you''re queuing for'),
 ('The queue you''re standing in right now.',4,'text','Is it always this long at this time?'),
 ('The queue you''re standing in right now.',5,'photo','Show me what''s in your hand while you wait'),
 ('The queue you''re standing in right now.',6,'text','Be honest — is it worth the wait?'),

 ('The spot on campus you''d defend in an argument.',1,'photo','Show me it right now'),
 ('The spot on campus you''d defend in an argument.',2,'text','What''s your actual argument for it?'),
 ('The spot on campus you''d defend in an argument.',3,'photo','Show me the detail people miss'),
 ('The spot on campus you''d defend in an argument.',4,'text','How often are you there?'),
 ('The spot on campus you''d defend in an argument.',5,'photo','Show me the spot you''d never defend'),
 ('The spot on campus you''d defend in an argument.',6,'text','Who introduced you to it?'),

 ('Whatever the weather is doing right now, from where you are.',1,'photo','Show me the sky directly above you'),
 ('Whatever the weather is doing right now, from where you are.',2,'text','Did you dress for this?'),
 ('Whatever the weather is doing right now, from where you are.',3,'photo','Show me your shoes in it'),
 ('Whatever the weather is doing right now, from where you are.',4,'text','How''s the walk to the gate going to be?'),
 ('Whatever the weather is doing right now, from where you are.',5,'photo','Show me indoors from where you are'),
 ('Whatever the weather is doing right now, from where you are.',6,'text','Be honest — umbrella in the bag or not?'),

 ('Show sunrise from wherever you were.',1,'photo','Show me who else was there for it'),
 ('Show sunrise from wherever you were.',2,'text','How early did you have to wake up?'),
 ('Show sunrise from wherever you were.',3,'photo','Show me the exact moment it broke the horizon'),
 ('Show sunrise from wherever you were.',4,'text','Was it worth the wake-up?'),
 ('Show sunrise from wherever you were.',5,'photo','Show me a sunrise you missed instead'),
 ('Show sunrise from wherever you were.',6,'text','Be honest — did you almost sleep through it?'),

 ('Show your shoes'' condition.',1,'photo','Show me the trail they just came off'),
 ('Show your shoes'' condition.',2,'text','How many treks have they survived?'),
 ('Show your shoes'' condition.',3,'photo','Show me the soles up close'),
 ('Show your shoes'' condition.',4,'text','Are they done for after this one?'),
 ('Show your shoes'' condition.',5,'photo','Show me your first-ever trekking shoes'),
 ('Show your shoes'' condition.',6,'text','Be honest — did your feet survive better?'),

 ('The bag you pack.',1,'photo','Show me everything laid out from inside it'),
 ('The bag you pack.',2,'text','What do you always forget?'),
 ('The bag you pack.',3,'photo','Show me the heaviest thing in it'),
 ('The bag you pack.',4,'text','How long does packing actually take you?'),
 ('The bag you pack.',5,'photo','Show me someone else''s pack for comparison'),
 ('The bag you pack.',6,'text','Be honest — did you overpack again?'),

 ('The blister/scrape/scar.',1,'photo','Show me where it happened'),
 ('The blister/scrape/scar.',2,'text','Did you keep going after?'),
 ('The blister/scrape/scar.',3,'photo','Show me it up close'),
 ('The blister/scrape/scar.',4,'text','How long ago did you get it?'),
 ('The blister/scrape/scar.',5,'photo','Show me an older scar from a different trek'),
 ('The blister/scrape/scar.',6,'text','Be honest — was it avoidable?'),

 ('The view you''d go back for.',1,'photo','Show me the climb to get there'),
 ('The view you''d go back for.',2,'text','How long did it take to reach it?'),
 ('The view you''d go back for.',3,'photo','Show me the exact detail that makes it worth it'),
 ('The view you''d go back for.',4,'text','Who were you with when you first saw it?'),
 ('The view you''d go back for.',5,'photo','Show me a view that disappointed you instead'),
 ('The view you''d go back for.',6,'text','Be honest — will you actually go back?'),

 ('Your favourite spot within 100km.',1,'photo','Show me the road or trail to get there'),
 ('Your favourite spot within 100km.',2,'text','How did you first find it?'),
 ('Your favourite spot within 100km.',3,'photo','Show me the exact detail you love'),
 ('Your favourite spot within 100km.',4,'text','How many times have you been back?'),
 ('Your favourite spot within 100km.',5,'photo','Show me a spot that''s overrated instead'),
 ('Your favourite spot within 100km.',6,'text','Be honest — are you gatekeeping this one?'),

 ('Your last trek''s summit photo.',1,'photo','Show me who else made it to the top'),
 ('Your last trek''s summit photo.',2,'text','How long did the climb take?'),
 ('Your last trek''s summit photo.',3,'photo','Show me your legs or shoes at the summit'),
 ('Your last trek''s summit photo.',4,'text','Was it harder than you expected?'),
 ('Your last trek''s summit photo.',5,'photo','Show me the trek you''re doing next'),
 ('Your last trek''s summit photo.',6,'text','Be honest — did you almost give up partway?'),

 ('Your water bottle at the end.',1,'photo','Show me it full, from the start'),
 ('Your water bottle at the end.',2,'text','Did you ration it right?'),
 ('Your water bottle at the end.',3,'photo','Show me exactly how much is left'),
 ('Your water bottle at the end.',4,'text','How far did you actually cover?'),
 ('Your water bottle at the end.',5,'photo','Show me someone else''s bottle for comparison'),
 ('Your water bottle at the end.',6,'text','Be honest — did you nearly run out?')
)
INSERT INTO public.ping_prompts (prompt_text, daily_prompt_id, pool, prompt_kind, active, created_at)
SELECT s.txt, dp.id, 'linked', s.kind, true, now() + (s.slot * interval '1 millisecond')
FROM src s
JOIN public.daily_prompts dp ON dp.prompt_text = s.parent AND dp.active
WHERE NOT EXISTS (
  SELECT 1 FROM public.ping_prompts pp
   WHERE pp.daily_prompt_id = dp.id AND pp.prompt_text = s.txt AND pp.active
);
