WITH src(parent, slot, kind, txt) AS (VALUES
 -- Foodies
 ('Chai/coffee in your hand.',1,'photo','Show me where you got it'),
 ('Chai/coffee in your hand.',2,'text','How many today?'),
 ('Chai/coffee in your hand.',3,'photo','Show me the cup when it''s empty'),
 ('Chai/coffee in your hand.',4,'text','What''s your actual order?'),
 ('Chai/coffee in your hand.',5,'photo','Show me who you''re drinking it with'),
 ('Chai/coffee in your hand.',6,'text','Be honest — chai or coffee person?'),

 ('Show ₹50 worth of food near campus.',1,'photo','Show me the place you got it'),
 ('Show ₹50 worth of food near campus.',2,'text','Is ₹50 still enough?'),
 ('Show ₹50 worth of food near campus.',3,'photo','Show me it eaten'),
 ('Show ₹50 worth of food near campus.',4,'text','What''s the best value item anywhere near here?'),
 ('Show ₹50 worth of food near campus.',5,'photo','Show me your wallet or UPI screen'),
 ('Show ₹50 worth of food near campus.',6,'text','Be honest — how much do you spend a day?'),

 ('Show the place you go when mess food loses.',1,'photo','Show me what you order there'),
 ('Show the place you go when mess food loses.',2,'text','How many times a week?'),
 ('Show the place you go when mess food loses.',3,'photo','Show me the walk or ride to get there'),
 ('Show the place you go when mess food loses.',4,'text','Who do you usually go with?'),
 ('Show the place you go when mess food loses.',5,'photo','Show me tonight''s mess food for comparison'),
 ('Show the place you go when mess food loses.',6,'text','Be honest — what does it cost you monthly?'),

 ('The canteen''s best-kept secret.',1,'photo','Show me it on the plate'),
 ('The canteen''s best-kept secret.',2,'text','Who told you about it?'),
 ('The canteen''s best-kept secret.',3,'photo','Show me the counter it''s at'),
 ('The canteen''s best-kept secret.',4,'text','What time does it run out?'),
 ('The canteen''s best-kept secret.',5,'photo','Show me the thing everyone orders instead'),
 ('The canteen''s best-kept secret.',6,'text','Be honest — are you annoyed you shared it?'),

 ('The snack in your bag right now.',1,'photo','Show me the whole bag'),
 ('The snack in your bag right now.',2,'text','How long has it been in there?'),
 ('The snack in your bag right now.',3,'photo','Show me it opened'),
 ('The snack in your bag right now.',4,'text','Emergency snack or today''s snack?'),
 ('The snack in your bag right now.',5,'photo','Show me what you''d rather be eating'),
 ('The snack in your bag right now.',6,'text','Be honest — would you share it?'),

 ('What you''re eating. Right now. No staging.',1,'photo','Show me where you''re eating it'),
 ('What you''re eating. Right now. No staging.',2,'text','Is this lunch or something else?'),
 ('What you''re eating. Right now. No staging.',3,'photo','Show me what''s left after'),
 ('What you''re eating. Right now. No staging.',4,'text','Who made it?'),
 ('What you''re eating. Right now. No staging.',5,'photo','Show me your hands'),
 ('What you''re eating. Right now. No staging.',6,'text','Be honest — is it good?'),

 ('Your midnight food setup.',1,'photo','Show me the room while you eat it'),
 ('Your midnight food setup.',2,'text','What time is it actually?'),
 ('Your midnight food setup.',3,'photo','Show me the wrapper pile'),
 ('Your midnight food setup.',4,'text','How often is this a thing?'),
 ('Your midnight food setup.',5,'photo','Show me who''s awake with you'),
 ('Your midnight food setup.',6,'text','Be honest — is this dinner or a second dinner?'),

 ('Your order, exactly as it always is.',1,'photo','Show me the place'),
 ('Your order, exactly as it always is.',2,'text','How long has it been your order?'),
 ('Your order, exactly as it always is.',3,'photo','Show me the modification you always ask for'),
 ('Your order, exactly as it always is.',4,'text','Have you ever ordered anything else there?'),
 ('Your order, exactly as it always is.',5,'photo','Show me what your friend orders'),
 ('Your order, exactly as it always is.',6,'text','Be honest — do they know your order by now?'),

 -- Music
 ('A chord/riff you''re stuck on — photo of your hand on it.',1,'photo','Show me the instrument''s full body'),
 ('A chord/riff you''re stuck on — photo of your hand on it.',2,'text','How long have you been stuck on it?'),
 ('A chord/riff you''re stuck on — photo of your hand on it.',3,'photo','Show me your fingers up close'),
 ('A chord/riff you''re stuck on — photo of your hand on it.',4,'text','Who taught it to you, or did you self-teach?'),
 ('A chord/riff you''re stuck on — photo of your hand on it.',5,'photo','Show me a chord you''ve actually mastered'),
 ('A chord/riff you''re stuck on — photo of your hand on it.',6,'text','Be honest — is your technique actually right?'),

 ('hows your day',1,'photo','Show me where you are right now'),
 ('hows your day',2,'text','What''s been the best part so far?'),
 ('hows your day',3,'photo','Show me what you''re holding'),
 ('hows your day',4,'text','What are you looking forward to still?'),
 ('hows your day',5,'photo','Show me your face right now'),
 ('hows your day',6,'text','Be honest — has it actually been a good one?'),

 ('Show where you go to play without being heard.',1,'photo','Show me the walk to get there'),
 ('Show where you go to play without being heard.',2,'text','How did you find this spot?'),
 ('Show where you go to play without being heard.',3,'photo','Show me the corner you actually sit in'),
 ('Show where you go to play without being heard.',4,'text','Has anyone ever caught you there?'),
 ('Show where you go to play without being heard.',5,'photo','Show me a spot where you don''t mind being heard'),
 ('Show where you go to play without being heard.',6,'text','Be honest — are you actually good enough to be heard?'),

 ('Show your most-played song''s album art and defend it.',1,'photo','Show me your play count for it'),
 ('Show your most-played song''s album art and defend it.',2,'text','What''s your actual defense?'),
 ('Show your most-played song''s album art and defend it.',3,'photo','Show me the album art up close'),
 ('Show your most-played song''s album art and defend it.',4,'text','How long has it held the top spot?'),
 ('Show your most-played song''s album art and defend it.',5,'photo','Show me your most-skipped song instead'),
 ('Show your most-played song''s album art and defend it.',6,'text','Be honest — is it actually a good song?'),

 ('What''s playing right now. Screenshot it.',1,'photo','Show me what you''re doing while it plays'),
 ('What''s playing right now. Screenshot it.',2,'text','Did you pick it or did the algorithm?'),
 ('What''s playing right now. Screenshot it.',3,'photo','Show me the queue right after it'),
 ('What''s playing right now. Screenshot it.',4,'text','How many times have you heard it this week?'),
 ('What''s playing right now. Screenshot it.',5,'photo','Show me what was playing an hour ago'),
 ('What''s playing right now. Screenshot it.',6,'text','Be honest — does anyone know you like this?'),

 ('Your headphones. The real condition.',1,'photo','Show me the case they came in'),
 ('Your headphones. The real condition.',2,'text','How long have you had them?'),
 ('Your headphones. The real condition.',3,'photo','Show me the worn part up close'),
 ('Your headphones. The real condition.',4,'text','What finally broke on them?'),
 ('Your headphones. The real condition.',5,'photo','Show me your backup pair, if you have one'),
 ('Your headphones. The real condition.',6,'text','Be honest — should you have replaced these already?'),

 ('Your instrument where it''s currently sitting.',1,'photo','Show me the room around it'),
 ('Your instrument where it''s currently sitting.',2,'text','When did you last actually play it?'),
 ('Your instrument where it''s currently sitting.',3,'photo','Show me the wear on it up close'),
 ('Your instrument where it''s currently sitting.',4,'text','How long have you owned it?'),
 ('Your instrument where it''s currently sitting.',5,'photo','Show me an instrument you wish you played'),
 ('Your instrument where it''s currently sitting.',6,'text','Be honest — is it in tune right now?'),

 ('Your practice corner.',1,'photo','Show me what''s just outside it'),
 ('Your practice corner.',2,'text','How long have you used this spot?'),
 ('Your practice corner.',3,'photo','Show me the floor or wall up close'),
 ('Your practice corner.',4,'text','Does anyone complain about the noise?'),
 ('Your practice corner.',5,'photo','Show me a corner you wish you had instead'),
 ('Your practice corner.',6,'text','Be honest — do you skip days here?'),

 ('Your Spotify wrapped regret.',1,'photo','Show me the actual number next to it'),
 ('Your Spotify wrapped regret.',2,'text','Would you defend it anyway?'),
 ('Your Spotify wrapped regret.',3,'photo','Show me the artist or song up close'),
 ('Your Spotify wrapped regret.',4,'text','Did anyone see it before you could hide it?'),
 ('Your Spotify wrapped regret.',5,'photo','Show me the stat you''re actually proud of'),
 ('Your Spotify wrapped regret.',6,'text','Be honest — will next year''s be worse?'),

 -- Media (Anime/Movies)
 ('Show a physical book you actually own.',1,'photo','Show me the shelf it came from'),
 ('Show a physical book you actually own.',2,'text','Have you actually finished it?'),
 ('Show a physical book you actually own.',3,'photo','Show me the cover up close'),
 ('Show a physical book you actually own.',4,'text','Who gave it to you, or did you buy it?'),
 ('Show a physical book you actually own.',5,'photo','Show me the book you haven''t opened yet'),
 ('Show a physical book you actually own.',6,'text','Be honest — do you even read physical books?'),

 ('Show where you watch/read on campus.',1,'photo','Show me who else is nearby'),
 ('Show where you watch/read on campus.',2,'text','How did you find this spot?'),
 ('Show where you watch/read on campus.',3,'photo','Show me the exact seat or corner'),
 ('Show where you watch/read on campus.',4,'text','How long have you used it?'),
 ('Show where you watch/read on campus.',5,'photo','Show me a spot you''d rather have'),
 ('Show where you watch/read on campus.',6,'text','Be honest — do you actually focus there?'),

 ('Show your shelf, however chaotic.',1,'photo','Show me the messiest section'),
 ('Show your shelf, however chaotic.',2,'text','Is there an order to this, honestly?'),
 ('Show your shelf, however chaotic.',3,'photo','Show me the item you''re proudest of'),
 ('Show your shelf, however chaotic.',4,'text','How long did it take to build this collection?'),
 ('Show your shelf, however chaotic.',5,'photo','Show me someone else''s shelf'),
 ('Show your shelf, however chaotic.',6,'text','Be honest — have you used everything on it?'),

 ('The recommendation that ruined you.',1,'photo','Show me where you were when you finished it'),
 ('The recommendation that ruined you.',2,'text','Who recommended it to you?'),
 ('The recommendation that ruined you.',3,'photo','Show me the exact scene or page'),
 ('The recommendation that ruined you.',4,'text','How long did it take you to recover?'),
 ('The recommendation that ruined you.',5,'photo','Show me a recommendation you regret giving someone else'),
 ('The recommendation that ruined you.',6,'text','Be honest — would you go through it again?'),

 ('The scene you rewind every time.',1,'photo','Show me the screen paused on it'),
 ('The scene you rewind every time.',2,'text','How many times have you rewound it?'),
 ('The scene you rewind every time.',3,'photo','Show me the exact frame'),
 ('The scene you rewind every time.',4,'text','What makes it worth replaying?'),
 ('The scene you rewind every time.',5,'photo','Show me a scene you always skip instead'),
 ('The scene you rewind every time.',6,'text','Be honest — does it still hit the same?'),

 ('Your comfort rewatch, paused on your favourite frame.',1,'photo','Show me what''s around you while watching'),
 ('Your comfort rewatch, paused on your favourite frame.',2,'text','How many times have you seen it total?'),
 ('Your comfort rewatch, paused on your favourite frame.',3,'photo','Show me the frame itself, paused'),
 ('Your comfort rewatch, paused on your favourite frame.',4,'text','When did you first watch it?'),
 ('Your comfort rewatch, paused on your favourite frame.',5,'photo','Show me something new you''re watching instead'),
 ('Your comfort rewatch, paused on your favourite frame.',6,'text','Be honest — do you know the dialogue by heart?'),

 ('Your current watch/read. Frame or cover.',1,'photo','Show me where you''re consuming it'),
 ('Your current watch/read. Frame or cover.',2,'text','How far in are you?'),
 ('Your current watch/read. Frame or cover.',3,'photo','Show me the exact frame or page'),
 ('Your current watch/read. Frame or cover.',4,'text','Would you actually recommend it so far?'),
 ('Your current watch/read. Frame or cover.',5,'photo','Show me what you finished right before this'),
 ('Your current watch/read. Frame or cover.',6,'text','Be honest — are you going to finish it?'),

 ('Your watchlist, honestly long.',1,'photo','Show me the top of the list'),
 ('Your watchlist, honestly long.',2,'text','What''s the oldest thing still on it?'),
 ('Your watchlist, honestly long.',3,'photo','Show me the total count up close'),
 ('Your watchlist, honestly long.',4,'text','What''s actually next?'),
 ('Your watchlist, honestly long.',5,'photo','Show me your completed list for comparison'),
 ('Your watchlist, honestly long.',6,'text','Be honest — will you ever finish this list?'),

 -- Memes
 ('Show the group chat''s current running joke.',1,'photo','Show me who started it'),
 ('Show the group chat''s current running joke.',2,'text','How long has it been running?'),
 ('Show the group chat''s current running joke.',3,'photo','Show me the exact message that started it'),
 ('Show the group chat''s current running joke.',4,'text','Would an outsider even get it?'),
 ('Show the group chat''s current running joke.',5,'photo','Show me the joke that finally died'),
 ('Show the group chat''s current running joke.',6,'text','Be honest — is it still funny or just habit?'),

 ('Show your camera roll''s screenshot folder.',1,'photo','Show me the total count'),
 ('Show your camera roll''s screenshot folder.',2,'text','What''s actually in there you''d never share?'),
 ('Show your camera roll''s screenshot folder.',3,'photo','Show me the oldest one still saved'),
 ('Show your camera roll''s screenshot folder.',4,'text','When did you last clean it out?'),
 ('Show your camera roll''s screenshot folder.',5,'photo','Show me the most recent one'),
 ('Show your camera roll''s screenshot folder.',6,'text','Be honest — could you explain every screenshot in there?'),

 ('Something here that looks staged but isn''t.',1,'photo','Show me it from a different angle'),
 ('Something here that looks staged but isn''t.',2,'text','What actually happened here?'),
 ('Something here that looks staged but isn''t.',3,'photo','Show me the detail that gives it away as real'),
 ('Something here that looks staged but isn''t.',4,'text','Did anyone believe you when you told them?'),
 ('Something here that looks staged but isn''t.',5,'photo','Show me something you actually did stage once'),
 ('Something here that looks staged but isn''t.',6,'text','Be honest — did you get lucky with the timing?'),

 ('Something on campus that''s already a meme.',1,'photo','Show me it in its natural state'),
 ('Something on campus that''s already a meme.',2,'text','Who made it a meme first?'),
 ('Something on campus that''s already a meme.',3,'photo','Show me the exact detail people joke about'),
 ('Something on campus that''s already a meme.',4,'text','How long has it been a running joke?'),
 ('Something on campus that''s already a meme.',5,'photo','Show me something that deserves to be a meme but isn''t yet'),
 ('Something on campus that''s already a meme.',6,'text','Be honest — are you tired of the joke yet?'),

 ('The last meme you saved. No curating.',1,'photo','Show me the folder it''s sitting in'),
 ('The last meme you saved. No curating.',2,'text','Who sent it to you?'),
 ('The last meme you saved. No curating.',3,'photo','Show me it full-screen'),
 ('The last meme you saved. No curating.',4,'text','Have you sent it to anyone yet?'),
 ('The last meme you saved. No curating.',5,'photo','Show me the meme before it'),
 ('The last meme you saved. No curating.',6,'text','Be honest — is it actually funny or just relatable?'),

 ('The meme you''ve reused too many times.',1,'photo','Show me the last chat you sent it in'),
 ('The meme you''ve reused too many times.',2,'text','How many times have you actually sent it?'),
 ('The meme you''ve reused too many times.',3,'photo','Show me it full-screen'),
 ('The meme you''ve reused too many times.',4,'text','Has anyone called you out on it?'),
 ('The meme you''ve reused too many times.',5,'photo','Show me a meme you''ve retired'),
 ('The meme you''ve reused too many times.',6,'text','Be honest — are you going to send it again this week?'),

 ('Your gallery''s oldest saved meme.',1,'photo','Show me the date it was saved'),
 ('Your gallery''s oldest saved meme.',2,'text','Does it still make sense to you?'),
 ('Your gallery''s oldest saved meme.',3,'photo','Show me it full-screen'),
 ('Your gallery''s oldest saved meme.',4,'text','Who sent it, if you remember?'),
 ('Your gallery''s oldest saved meme.',5,'photo','Show me your most recently saved one'),
 ('Your gallery''s oldest saved meme.',6,'text','Be honest — why has it survived this long?'),

 ('Your most-sent reaction image.',1,'photo','Show me the last chat you sent it in'),
 ('Your most-sent reaction image.',2,'text','What situation is it always for?'),
 ('Your most-sent reaction image.',3,'photo','Show me it full-screen'),
 ('Your most-sent reaction image.',4,'text','How long have you used this one?'),
 ('Your most-sent reaction image.',5,'photo','Show me your second most-used one'),
 ('Your most-sent reaction image.',6,'text','Be honest — do people know it''s coming?'),

 -- Gaming
 ('Show your first-ever profile picture on any game.',1,'photo','Show me your current one for comparison'),
 ('Show your first-ever profile picture on any game.',2,'text','Do you remember why you picked it?'),
 ('Show your first-ever profile picture on any game.',3,'photo','Show me it up close'),
 ('Show your first-ever profile picture on any game.',4,'text','How old were you when you made it?'),
 ('Show your first-ever profile picture on any game.',5,'photo','Show me the account it belongs to now'),
 ('Show your first-ever profile picture on any game.',6,'text','Be honest — is it embarrassing?'),

 ('Show your hands mid-game.',1,'photo','Show me the screen they''re playing on'),
 ('Show your hands mid-game.',2,'text','Are you winning right now?'),
 ('Show your hands mid-game.',3,'photo','Show me your controller or keyboard up close'),
 ('Show your hands mid-game.',4,'text','How long have you been playing today?'),
 ('Show your hands mid-game.',5,'photo','Show me a teammate''s hands too, if you can'),
 ('Show your hands mid-game.',6,'text','Be honest — are your hands actually sweating?'),

 ('Show your rank. Own it.',1,'photo','Show me the match you just played'),
 ('Show your rank. Own it.',2,'text','Is this your peak or your slump?'),
 ('Show your rank. Own it.',3,'photo','Show me the rank badge up close'),
 ('Show your rank. Own it.',4,'text','How long did it take to get here?'),
 ('Show your rank. Own it.',5,'photo','Show me your very first rank ever'),
 ('Show your rank. Own it.',6,'text','Be honest — do you deserve this rank?'),

 ('The game you keep uninstalling and reinstalling.',1,'photo','Show me your install screen right now'),
 ('The game you keep uninstalling and reinstalling.',2,'text','How many times has this happened?'),
 ('The game you keep uninstalling and reinstalling.',3,'photo','Show me the exact icon'),
 ('The game you keep uninstalling and reinstalling.',4,'text','What always brings you back?'),
 ('The game you keep uninstalling and reinstalling.',5,'photo','Show me a game you''ve never uninstalled'),
 ('The game you keep uninstalling and reinstalling.',6,'text','Be honest — will it happen again this month?'),

 ('The teammate who carries you (their screen name).',1,'photo','Show me a screenshot of them playing'),
 ('The teammate who carries you (their screen name).',2,'text','Do they know they carry you?'),
 ('The teammate who carries you (their screen name).',3,'photo','Show me their name up close in-game'),
 ('The teammate who carries you (their screen name).',4,'text','How long have you played together?'),
 ('The teammate who carries you (their screen name).',5,'photo','Show me the teammate who carries THEM'),
 ('The teammate who carries you (their screen name).',6,'text','Be honest — have you ever carried them back?'),

 ('Your current game''s screen, paused.',1,'photo','Show me what''s just off-screen'),
 ('Your current game''s screen, paused.',2,'text','What were you about to do?'),
 ('Your current game''s screen, paused.',3,'photo','Show me your health or score bar'),
 ('Your current game''s screen, paused.',4,'text','How long have you been playing this session?'),
 ('Your current game''s screen, paused.',5,'photo','Show me the last game you paused'),
 ('Your current game''s screen, paused.',6,'text','Be honest — are you going to win this one?'),

 ('Your longest session''s clock.',1,'photo','Show me where you were sitting for it'),
 ('Your longest session''s clock.',2,'text','What did you skip to play that long?'),
 ('Your longest session''s clock.',3,'photo','Show me the exact time up close'),
 ('Your longest session''s clock.',4,'text','How did you feel right after?'),
 ('Your longest session''s clock.',5,'photo','Show me today''s session for comparison'),
 ('Your longest session''s clock.',6,'text','Be honest — was it worth it?'),

 ('Your setup — phone, PC, whatever.',1,'photo','Show me the rest of the room around it'),
 ('Your setup — phone, PC, whatever.',2,'text','What would you upgrade first?'),
 ('Your setup — phone, PC, whatever.',3,'photo','Show me the part you''re proudest of'),
 ('Your setup — phone, PC, whatever.',4,'text','How long did it take to put together?'),
 ('Your setup — phone, PC, whatever.',5,'photo','Show me someone else''s setup'),
 ('Your setup — phone, PC, whatever.',6,'text','Be honest — did you overspend on it?'),

 -- Pets & Strays
 ('Feeding spot.',1,'photo','Show me who''s waiting there right now'),
 ('Feeding spot.',2,'text','How long have you been feeding here?'),
 ('Feeding spot.',3,'photo','Show me the bowl or spot up close'),
 ('Feeding spot.',4,'text','Who else helps out?'),
 ('Feeding spot.',5,'photo','Show me a different feeding spot on campus'),
 ('Feeding spot.',6,'text','Be honest — do you spend money on this?'),

 ('Show an animal doing something absurd.',1,'photo','Show me where this happened'),
 ('Show an animal doing something absurd.',2,'text','Did it know you were watching?'),
 ('Show an animal doing something absurd.',3,'photo','Show me the exact moment up close'),
 ('Show an animal doing something absurd.',4,'text','How long did it keep doing it?'),
 ('Show an animal doing something absurd.',5,'photo','Show me a calmer moment from the same animal'),
 ('Show an animal doing something absurd.',6,'text','Be honest — did you laugh out loud?'),

 ('Show who''s sleeping where they shouldn''t.',1,'photo','Show me where they''re supposed to sleep instead'),
 ('Show who''s sleeping where they shouldn''t.',2,'text','How did they even get there?'),
 ('Show who''s sleeping where they shouldn''t.',3,'photo','Show me their face up close'),
 ('Show who''s sleeping where they shouldn''t.',4,'text','How long have they been asleep?'),
 ('Show who''s sleeping where they shouldn''t.',5,'photo','Show me them awake, for contrast'),
 ('Show who''s sleeping where they shouldn''t.',6,'text','Be honest — are you going to move them?'),

 ('The campus dog you''re loyal to.',1,'photo','Show me where it usually sleeps'),
 ('The campus dog you''re loyal to.',2,'text','Does it have a name, or just yours for it?'),
 ('The campus dog you''re loyal to.',3,'photo','Show me the dog''s face properly'),
 ('The campus dog you''re loyal to.',4,'text','How long has it been around?'),
 ('The campus dog you''re loyal to.',5,'photo','Show me who else stops to feed it'),
 ('The campus dog you''re loyal to.',6,'text','Be honest — does it come to you or to your food?'),

 ('The cat that owns this building.',1,'photo','Show me the spot it claims most'),
 ('The cat that owns this building.',2,'text','Who actually feeds it?'),
 ('The cat that owns this building.',3,'photo','Show me its face up close'),
 ('The cat that owns this building.',4,'text','How long has it lived here?'),
 ('The cat that owns this building.',5,'photo','Show me it somewhere it definitely shouldn''t be'),
 ('The cat that owns this building.',6,'text','Be honest — does it actually like anyone?'),

 ('The one that recognizes you.',1,'photo','Show me where you usually meet'),
 ('The one that recognizes you.',2,'text','How did it start recognizing you?'),
 ('The one that recognizes you.',3,'photo','Show me it looking at you, if you can catch it'),
 ('The one that recognizes you.',4,'text','How long has this been going on?'),
 ('The one that recognizes you.',5,'photo','Show me an animal that ignores you completely'),
 ('The one that recognizes you.',6,'text','Be honest — do you save it treats?'),

 ('Your pet at home — the photo in your gallery.',1,'photo','Show me the room they''re usually in'),
 ('Your pet at home — the photo in your gallery.',2,'text','How long since you''ve seen them in person?'),
 ('Your pet at home — the photo in your gallery.',3,'photo','Show me their face up close'),
 ('Your pet at home — the photo in your gallery.',4,'text','Do they still remember you between visits?'),
 ('Your pet at home — the photo in your gallery.',5,'photo','Show me a campus animal that reminds you of them'),
 ('Your pet at home — the photo in your gallery.',6,'text','Be honest — do you miss them right now?'),

 ('Your phone''s animal photo count.',1,'photo','Show me the most recent one'),
 ('Your phone''s animal photo count.',2,'text','Which animal has the most photos?'),
 ('Your phone''s animal photo count.',3,'photo','Show me the exact count up close'),
 ('Your phone''s animal photo count.',4,'text','How long did it take to reach this number?'),
 ('Your phone''s animal photo count.',5,'photo','Show me your photo count of actual people for comparison'),
 ('Your phone''s animal photo count.',6,'text','Be honest — is this too many?')
)
INSERT INTO public.ping_prompts (prompt_text, daily_prompt_id, pool, prompt_kind, active, created_at)
SELECT s.txt, dp.id, 'linked', s.kind, true, now() + (s.slot * interval '1 millisecond')
FROM src s
JOIN public.daily_prompts dp ON dp.prompt_text = s.parent AND dp.active
WHERE NOT EXISTS (
  SELECT 1 FROM public.ping_prompts pp
   WHERE pp.daily_prompt_id = dp.id AND pp.prompt_text = s.txt
);
